//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.0.0.1 (2017-7-21 11:15) 受影响文件：所有
        ///	1、上线第一次测试
        ///
        ///1.0.0.2 (2017-8-23 16:35) 受影响文件：App_OP,CIS,CIS.Model,CIS.Core
        ///	1、增加诊断重复检测功能
        ///	2、增加药品项目重复检测功能
        ///	3、优化主界面加载速度(异步加载检验检查数据)
        ///	4、修复了一个BUG,该BUG导致在常用诊断中导入诊断会无法识别中医诊断或者西医诊断
        ///	5、抛弃事件总线,使用传入主窗体的方式调用公共方法,防止出现偶然性的错误
        ///	6、增加添加常用诊断时重复检测功能
        ///
        ///1.0.0.3 (2017-8-31 11:03) 受影响文件：App_OP,CIS,CIS.Purview
        ///	1、患者选择列表优化,所有首诊非本人的都放在科室选项卡中,本人选项卡中只放首诊是自己或者是专家号的病人
        ///	2、所有打印格式的调整,丹阳中医院的纸张是32开的纸
        ///	3、患者状态改变的时候更新挂号表的医生工号和医生姓名
        ///	4、解决草药套餐选择时不能全选某个文件夹下的项目
        ///	5、修复了一个BUG,该BUG导致模板设置中不能修改已经做好的模板
        ///	6、修 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一个数字：修改日期是几几年
        ///第二个数字：修改日期是几月
        ///第三个数字：修改日期是几号
        ///第四个数字：当前修改是当天的第几次修改 的本地化字符串。
        /// </summary>
        internal static string 版本信息设计规则 {
            get {
                return ResourceManager.GetString("版本信息设计规则", resourceCulture);
            }
        }
    }
}
