//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类IView_HIS_ExamineItem 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_HIS_ExamineItem")]
	[Serializable]
	public partial class IView_HIS_ExamineItem : Entity 
	{
		#region Model
		private string _Code;
		private string _Name;
		private decimal? _Price;
		private string _Specimen;
		private string _TestTube;
		private string _DeptCode;
		private string _SearchCode;
		private string _ItemType;
		private string _WubiCode;
		/// <summary>
		/// 
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Price
		{
			get{ return _Price; }
			set
			{
				this.OnPropertyValueChange(_.Price,_Price,value);
				this._Price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Specimen
		{
			get{ return _Specimen; }
			set
			{
				this.OnPropertyValueChange(_.Specimen,_Specimen,value);
				this._Specimen=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TestTube
		{
			get{ return _TestTube; }
			set
			{
				this.OnPropertyValueChange(_.TestTube,_TestTube,value);
				this._TestTube=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange(_.DeptCode,_DeptCode,value);
				this._DeptCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ItemType
		{
			get{ return _ItemType; }
			set
			{
				this.OnPropertyValueChange(_.ItemType,_ItemType,value);
				this._ItemType=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string WubiCode
		{
			get{ return _WubiCode; }
			set
			{
				this.OnPropertyValueChange(_.WubiCode,_WubiCode,value);
				this._WubiCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Code,
				_.Name,
				_.Price,
				_.Specimen,
				_.TestTube,
				_.DeptCode,
				_.SearchCode,
				_.ItemType,
				_.WubiCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Code,
				this._Name,
				this._Price,
				this._Specimen,
				this._TestTube,
				this._DeptCode,
				this._SearchCode,
				this._ItemType,
				this._WubiCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","IView_HIS_ExamineItem");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code","IView_HIS_ExamineItem","Code");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","IView_HIS_ExamineItem","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Price = new Field("Price","IView_HIS_ExamineItem","Price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Specimen = new Field("Specimen","IView_HIS_ExamineItem","Specimen");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TestTube = new Field("TestTube","IView_HIS_ExamineItem","TestTube");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode","IView_HIS_ExamineItem","DeptCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","IView_HIS_ExamineItem","SearchCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ItemType = new Field("ItemType","IView_HIS_ExamineItem","ItemType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WubiCode = new Field("WubiCode","IView_HIS_ExamineItem","WubiCode");
		}
		#endregion


	}
}

