//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类IView_Inside_DealWithItem 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_Inside_DealWithItem")]
    [Serializable]
    public partial class IView_Inside_DealWithItem : Entity
    {
        #region Model
        private string _ID;
        private string _GroupID;
        private int? _Number;
        private int? _No;
        private string _Owner;
        private string _Code;
        private string _Name;
        private decimal? _Price;
        private string _SearchCode;
        private string _WubiCode;
        private string _PackingUnit;
        private string _Specification;
        private string _ExecuteDept;
        /// <summary>
        /// 
        /// </summary>
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange(_.ID, _ID, value);
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string GroupID
        {
            get { return _GroupID; }
            set
            {
                this.OnPropertyValueChange(_.GroupID, _GroupID, value);
                this._GroupID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Number
        {
            get { return _Number; }
            set
            {
                this.OnPropertyValueChange(_.Number, _Number, value);
                this._Number = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? No
        {
            get { return _No; }
            set
            {
                this.OnPropertyValueChange(_.No, _No, value);
                this._No = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Owner
        {
            get { return _Owner; }
            set
            {
                this.OnPropertyValueChange(_.Owner, _Owner, value);
                this._Owner = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Code
        {
            get { return _Code; }
            set
            {
                this.OnPropertyValueChange(_.Code, _Code, value);
                this._Code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange(_.Name, _Name, value);
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal? Price
        {
            get { return _Price; }
            set
            {
                this.OnPropertyValueChange(_.Price, _Price, value);
                this._Price = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SearchCode
        {
            get { return _SearchCode; }
            set
            {
                this.OnPropertyValueChange(_.SearchCode, _SearchCode, value);
                this._SearchCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string WubiCode
        {
            get { return _WubiCode; }
            set
            {
                this.OnPropertyValueChange(_.WubiCode, _WubiCode, value);
                this._WubiCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PackingUnit
        {
            get { return _PackingUnit; }
            set
            {
                this.OnPropertyValueChange(_.PackingUnit, _PackingUnit, value);
                this._PackingUnit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Specification
        {
            get { return _Specification; }
            set
            {
                this.OnPropertyValueChange(_.Specification, _Specification, value);
                this._Specification = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ExecuteDept
        {
            get { return _ExecuteDept; }
            set
            {
                this.OnPropertyValueChange(_.ExecuteDept, _ExecuteDept, value);
                this._ExecuteDept = value;
            }
        }

        #endregion

        #region Method
        /// <summary>
        /// 是否只读
        /// </summary>
        public override bool IsReadOnly()
        {
            return true;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.GroupID,
				_.Number,
				_.No,
				_.Owner,
				_.Code,
				_.Name,
				_.Price,
				_.SearchCode,
				_.WubiCode,
				_.PackingUnit,
				_.Specification,
				_.ExecuteDept};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._GroupID,
				this._Number,
				this._No,
				this._Owner,
				this._Code,
				this._Name,
				this._Price,
				this._SearchCode,
				this._WubiCode,
				this._PackingUnit,
				this._Specification,
				this._ExecuteDept};
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "IView_Inside_DealWithItem");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "IView_Inside_DealWithItem", "ID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field GroupID = new Field("GroupID", "IView_Inside_DealWithItem", "GroupID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Number = new Field("Number", "IView_Inside_DealWithItem", "Number");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field No = new Field("No", "IView_Inside_DealWithItem", "No");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Owner = new Field("Owner", "IView_Inside_DealWithItem", "Owner");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Code = new Field("Code", "IView_Inside_DealWithItem", "Code");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Name = new Field("Name", "IView_Inside_DealWithItem", "Name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Price = new Field("Price", "IView_Inside_DealWithItem", "Price");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SearchCode = new Field("SearchCode", "IView_Inside_DealWithItem", "SearchCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WubiCode = new Field("WubiCode", "IView_Inside_DealWithItem", "WubiCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PackingUnit = new Field("PackingUnit", "IView_Inside_DealWithItem", "PackingUnit");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Specification = new Field("Specification", "IView_Inside_DealWithItem", "Specification");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExecuteDept = new Field("ExecuteDept", "IView_Inside_DealWithItem", "ExecuteDept");

        }
        #endregion


    }
}

