//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类IView_PrescriptionCirculation_DrugInfo。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_PrescriptionCirculation_DrugInfo")]
    [Serializable]
    public partial class IView_PrescriptionCirculation_DrugInfo : Entity
    {
        #region Model
        private string _CityCode;
        private string _DrugName;
        private string _Specification;
        private string _PackingUnit;
        private string _NickName;
        private string _ProductionSites;
        private string _DrugCategory;
        private string _DrugForm;
        private string _MinDoseUnit;
        private string _SpellCode;

        /// <summary>
        /// 
        /// </summary>
        [Field("CityCode")]
        public string CityCode
        {
            get { return _CityCode; }
            set
            {
                this.OnPropertyValueChange("CityCode");
                this._CityCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DrugName")]
        public string DrugName
        {
            get { return _DrugName; }
            set
            {
                this.OnPropertyValueChange("DrugName");
                this._DrugName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Specification")]
        public string Specification
        {
            get { return _Specification; }
            set
            {
                this.OnPropertyValueChange("Specification");
                this._Specification = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PackingUnit")]
        public string PackingUnit
        {
            get { return _PackingUnit; }
            set
            {
                this.OnPropertyValueChange("PackingUnit");
                this._PackingUnit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("NickName")]
        public string NickName
        {
            get { return _NickName; }
            set
            {
                this.OnPropertyValueChange("NickName");
                this._NickName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ProductionSites")]
        public string ProductionSites
        {
            get { return _ProductionSites; }
            set
            {
                this.OnPropertyValueChange("ProductionSites");
                this._ProductionSites = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DrugCategory")]
        public string DrugCategory
        {
            get { return _DrugCategory; }
            set
            {
                this.OnPropertyValueChange("DrugCategory");
                this._DrugCategory = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DrugForm")]
        public string DrugForm
        {
            get { return _DrugForm; }
            set
            {
                this.OnPropertyValueChange("DrugForm");
                this._DrugForm = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MinDoseUnit")]
        public string MinDoseUnit
        {
            get { return _MinDoseUnit; }
            set
            {
                this.OnPropertyValueChange("MinDoseUnit");
                this._MinDoseUnit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SpellCode")]
        public string SpellCode
        {
            get { return _SpellCode; }
            set
            {
                this.OnPropertyValueChange("SpellCode");
                this._SpellCode = value;
            }
        }

        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.CityCode,
                _.DrugName,
                _.Specification,
                _.PackingUnit,
                _.NickName,
                _.ProductionSites,
                _.DrugCategory,
                _.DrugForm,
                _.MinDoseUnit,
                _.SpellCode
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._CityCode,
                this._DrugName,
                this._Specification,
                this._PackingUnit,
                this._NickName,
                this._ProductionSites,
                this._DrugCategory,
                this._DrugForm,
                this._MinDoseUnit,
                this._SpellCode
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "IView_PrescriptionCirculation_DrugInfo");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CityCode = new Field("CityCode", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DrugName = new Field("DrugName", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Specification = new Field("Specification", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PackingUnit = new Field("PackingUnit", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NickName = new Field("NickName", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductionSites = new Field("ProductionSites", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DrugCategory = new Field("DrugCategory", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DrugForm = new Field("DrugForm", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MinDoseUnit = new Field("MinDoseUnit", "IView_PrescriptionCirculation_DrugInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SpellCode = new Field("SpellCode", "IView_PrescriptionCirculation_DrugInfo", "");
        }
        #endregion
    }
}