//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类IView_HIS_DealWithItem 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_HIS_DealWithItem")]
    [Serializable]
    public partial class IView_HIS_DealWithItem : Entity
    {
        #region Model
        private string _Code;
        private string _Name;
        private decimal? _Price;
        private string _SearchCode;
        private string _WubiCode;
        private string _PackingUnit;
        private string _Specification;
        private string _ExecuteDept;
        private string _MedicalInsuranceDrugSerial;
        /// <summary>
        /// 
        /// </summary>
        public string Code
        {
            get { return _Code; }
            set
            {
                this.OnPropertyValueChange(_.Code, _Code, value);
                this._Code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange(_.Name, _Name, value);
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal? Price
        {
            get { return _Price; }
            set
            {
                this.OnPropertyValueChange(_.Price, _Price, value);
                this._Price = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SearchCode
        {
            get { return _SearchCode; }
            set
            {
                this.OnPropertyValueChange(_.SearchCode, _SearchCode, value);
                this._SearchCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string WubiCode
        {
            get { return _WubiCode; }
            set
            {
                this.OnPropertyValueChange(_.WubiCode, _WubiCode, value);
                this._WubiCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PackingUnit
        {
            get { return _PackingUnit; }
            set
            {
                this.OnPropertyValueChange(_.PackingUnit, _PackingUnit, value);
                this._PackingUnit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Specification
        {
            get { return _Specification; }
            set
            {
                this.OnPropertyValueChange(_.Specification, _Specification, value);
                this._Specification = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ExecuteDept
        {
            get { return _ExecuteDept; }
            set
            {
                this.OnPropertyValueChange(_.ExecuteDept, _ExecuteDept, value);
                this._ExecuteDept = value;
            }
        }
        /// <summary>
		/// 
		/// </summary>
		public string MedicalInsuranceDrugSerial
        {
            get { return _MedicalInsuranceDrugSerial; }
            set
            {
                this.OnPropertyValueChange(_.MedicalInsuranceDrugSerial, _MedicalInsuranceDrugSerial, value);
                this._MedicalInsuranceDrugSerial = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 是否只读
        /// </summary>
        public override bool IsReadOnly()
        {
            return true;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Code,
                _.Name,
                _.Price,
                _.SearchCode,
                _.WubiCode,
                _.PackingUnit,
                _.Specification,
                _.ExecuteDept,
            _.MedicalInsuranceDrugSerial};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Code,
                this._Name,
                this._Price,
                this._SearchCode,
                this._WubiCode,
                this._PackingUnit,
                this._Specification,
                this._ExecuteDept,
            this._MedicalInsuranceDrugSerial};
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "IView_HIS_DealWithItem");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Code = new Field("Code", "IView_HIS_DealWithItem", "Code");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Name = new Field("Name", "IView_HIS_DealWithItem", "Name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Price = new Field("Price", "IView_HIS_DealWithItem", "Price");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SearchCode = new Field("SearchCode", "IView_HIS_DealWithItem", "SearchCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WubiCode = new Field("WubiCode", "IView_HIS_DealWithItem", "WubiCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PackingUnit = new Field("PackingUnit", "IView_HIS_DealWithItem", "PackingUnit");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Specification = new Field("Specification", "IView_HIS_DealWithItem", "Specification");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExecuteDept = new Field("ExecuteDept", "IView_HIS_DealWithItem", "ExecuteDept");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MedicalInsuranceDrugSerial = new Field("MedicalInsuranceDrugSerial", "IView_HIS_DealWithItem", "MedicalInsuranceDrugSerial");
        }
        #endregion


    }
}

