//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类IView_HIS_Outpatients_All。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_HIS_Outpatients_All")]
    [Serializable]
    public partial class IView_HIS_Outpatients_All : Entity
    {
        #region Model
		private DateTime _RegisterTime;
		private string _OutpatientNo;
		private string _PatientID;
		private string _PatientName;
		private string _Sex;
		private DateTime? _Birthday;
		private string _Age;
		private string _DeptCode;
		private string _DeptName;
		private string _DoctorNo;
		private string _DoctorName;
		private string _RegisterNo;
		private string _PatientAddress;
		private string _ContactNumber;
		private string _Category;
		private string _EmerencyFlag;
		private string _PayType;
		private string _PayTypeCode;
		private string _CardNo;
		private string _SearchCode;
		private string _IDCard;
		private string _Address;
		private string _State;

		/// <summary>
		/// 
		/// </summary>
		[Field("RegisterTime")]
		public DateTime RegisterTime
		{
			get{ return _RegisterTime; }
			set
			{
				this.OnPropertyValueChange("RegisterTime");
				this._RegisterTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OutpatientNo")]
		public string OutpatientNo
		{
			get{ return _OutpatientNo; }
			set
			{
				this.OnPropertyValueChange("OutpatientNo");
				this._OutpatientNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PatientID")]
		public string PatientID
		{
			get{ return _PatientID; }
			set
			{
				this.OnPropertyValueChange("PatientID");
				this._PatientID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PatientName")]
		public string PatientName
		{
			get{ return _PatientName; }
			set
			{
				this.OnPropertyValueChange("PatientName");
				this._PatientName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Sex")]
		public string Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange("Sex");
				this._Sex = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Birthday")]
		public DateTime? Birthday
		{
			get{ return _Birthday; }
			set
			{
				this.OnPropertyValueChange("Birthday");
				this._Birthday = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Age")]
		public string Age
		{
			get{ return _Age; }
			set
			{
				this.OnPropertyValueChange("Age");
				this._Age = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptCode")]
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange("DeptCode");
				this._DeptCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptName")]
		public string DeptName
		{
			get{ return _DeptName; }
			set
			{
				this.OnPropertyValueChange("DeptName");
				this._DeptName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DoctorNo")]
		public string DoctorNo
		{
			get{ return _DoctorNo; }
			set
			{
				this.OnPropertyValueChange("DoctorNo");
				this._DoctorNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DoctorName")]
		public string DoctorName
		{
			get{ return _DoctorName; }
			set
			{
				this.OnPropertyValueChange("DoctorName");
				this._DoctorName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegisterNo")]
		public string RegisterNo
		{
			get{ return _RegisterNo; }
			set
			{
				this.OnPropertyValueChange("RegisterNo");
				this._RegisterNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PatientAddress")]
		public string PatientAddress
		{
			get{ return _PatientAddress; }
			set
			{
				this.OnPropertyValueChange("PatientAddress");
				this._PatientAddress = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ContactNumber")]
		public string ContactNumber
		{
			get{ return _ContactNumber; }
			set
			{
				this.OnPropertyValueChange("ContactNumber");
				this._ContactNumber = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Category")]
		public string Category
		{
			get{ return _Category; }
			set
			{
				this.OnPropertyValueChange("Category");
				this._Category = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EmerencyFlag")]
		public string EmerencyFlag
		{
			get{ return _EmerencyFlag; }
			set
			{
				this.OnPropertyValueChange("EmerencyFlag");
				this._EmerencyFlag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PayType")]
		public string PayType
		{
			get{ return _PayType; }
			set
			{
				this.OnPropertyValueChange("PayType");
				this._PayType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PayTypeCode")]
		public string PayTypeCode
		{
			get{ return _PayTypeCode; }
			set
			{
				this.OnPropertyValueChange("PayTypeCode");
				this._PayTypeCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CardNo")]
		public string CardNo
		{
			get{ return _CardNo; }
			set
			{
				this.OnPropertyValueChange("CardNo");
				this._CardNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SearchCode")]
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange("SearchCode");
				this._SearchCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IDCard")]
		public string IDCard
		{
			get{ return _IDCard; }
			set
			{
				this.OnPropertyValueChange("IDCard");
				this._IDCard = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Address")]
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange("Address");
				this._Address = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("State")]
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.RegisterTime,
				_.OutpatientNo,
				_.PatientID,
				_.PatientName,
				_.Sex,
				_.Birthday,
				_.Age,
				_.DeptCode,
				_.DeptName,
				_.DoctorNo,
				_.DoctorName,
				_.RegisterNo,
				_.PatientAddress,
				_.ContactNumber,
				_.Category,
				_.EmerencyFlag,
				_.PayType,
				_.PayTypeCode,
				_.CardNo,
				_.SearchCode,
				_.IDCard,
				_.Address,
				_.State,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._RegisterTime,
				this._OutpatientNo,
				this._PatientID,
				this._PatientName,
				this._Sex,
				this._Birthday,
				this._Age,
				this._DeptCode,
				this._DeptName,
				this._DoctorNo,
				this._DoctorName,
				this._RegisterNo,
				this._PatientAddress,
				this._ContactNumber,
				this._Category,
				this._EmerencyFlag,
				this._PayType,
				this._PayTypeCode,
				this._CardNo,
				this._SearchCode,
				this._IDCard,
				this._Address,
				this._State,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "IView_HIS_Outpatients_All");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RegisterTime = new Field("RegisterTime", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OutpatientNo = new Field("OutpatientNo", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientID = new Field("PatientID", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientName = new Field("PatientName", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Birthday = new Field("Birthday", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Age = new Field("Age", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorNo = new Field("DoctorNo", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorName = new Field("DoctorName", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RegisterNo = new Field("RegisterNo", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientAddress = new Field("PatientAddress", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ContactNumber = new Field("ContactNumber", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Category = new Field("Category", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field EmerencyFlag = new Field("EmerencyFlag", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PayType = new Field("PayType", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PayTypeCode = new Field("PayTypeCode", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CardNo = new Field("CardNo", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IDCard = new Field("IDCard", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address", "IView_HIS_Outpatients_All", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State", "IView_HIS_Outpatients_All", "");
        }
        #endregion
	}
}