//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类IView_HIS_ICD 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_HIS_ICD")]
    [Serializable]
    public partial class IView_HIS_ICD : Entity
    {
        #region Model
        private string _Code;
        private string _Name;
        private string _SearchCode;
        private string _Type;
        private int _SpecialFlag;
        /// <summary>
        /// 
        /// </summary>
        public string Code
        {
            get { return _Code; }
            set
            {
                this.OnPropertyValueChange(_.Code, _Code, value);
                this._Code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange(_.Name, _Name, value);
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SearchCode
        {
            get { return _SearchCode; }
            set
            {
                this.OnPropertyValueChange(_.SearchCode, _SearchCode, value);
                this._SearchCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange(_.Type, _Type, value);
                this._Type = value;
            }
        }
        /// <summary>
        /// 特殊标志 0普通 1慢病 2传染病
        /// </summary>
        public int SpecialFlag
        {
            get { return _SpecialFlag; }
            set
            {
                this.OnPropertyValueChange(_.SpecialFlag, _SpecialFlag, value);
                this._SpecialFlag = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 是否只读
        /// </summary>
        public override bool IsReadOnly()
        {
            return true;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Code,
                _.Name,
                _.SearchCode,
                _.Type,
                _.SpecialFlag
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Code,
                this._Name,
                this._SearchCode,
                this._Type,
                this._SpecialFlag
            };
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "IView_HIS_ICD");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Code = new Field("Code", "IView_HIS_ICD", "Code");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Name = new Field("Name", "IView_HIS_ICD", "Name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SearchCode = new Field("SearchCode", "IView_HIS_ICD", "SearchCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Type = new Field("Type", "IView_HIS_ICD", "Type");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SpecialFlag = new Field("SpecialFlag", "IView_HIS_ICD", "SpecialFlag");
        }
        #endregion


    }
}

