//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类IView_HIS_ExamineItem_Detail 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_HIS_ExamineItem_Detail")]
	[Serializable]
	public partial class IView_HIS_ExamineItem_Detail : Entity 
	{
		#region Model
		private string _ItemCode;
		private string _Code;
		private string _Name;
		private decimal? _Price;
		private decimal? _Quantity;
		/// <summary>
		/// 
		/// </summary>
		public string ItemCode
		{
			get{ return _ItemCode; }
			set
			{
				this.OnPropertyValueChange(_.ItemCode,_ItemCode,value);
				this._ItemCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Price
		{
			get{ return _Price; }
			set
			{
				this.OnPropertyValueChange(_.Price,_Price,value);
				this._Price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Quantity
		{
			get{ return _Quantity; }
			set
			{
				this.OnPropertyValueChange(_.Quantity,_Quantity,value);
				this._Quantity=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ItemCode,
				_.Code,
				_.Name,
				_.Price,
				_.Quantity};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ItemCode,
				this._Code,
				this._Name,
				this._Price,
				this._Quantity};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","IView_HIS_ExamineItem_Detail");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ItemCode = new Field("ItemCode","IView_HIS_ExamineItem_Detail","ItemCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code","IView_HIS_ExamineItem_Detail","Code");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","IView_HIS_ExamineItem_Detail","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Price = new Field("Price","IView_HIS_ExamineItem_Detail","Price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Quantity = new Field("Quantity","IView_HIS_ExamineItem_Detail","Quantity");
		}
		#endregion


	}
}

