//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
	/// <summary>
	/// 实体类IView_HIS_LISResult。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("IView_HIS_LISResult")]
	[Serializable]
	public partial class IView_HIS_LISResult : Entity
	{
		#region Model
		//private string _blhjzh;
		//private string _HISXMNO;
		//private string _XMMC;
		//private int? _xmno;
		private DateTime? _ReceiveDate;
		private string _IDCard;
		private string _PatNo;
		private string _Cname;
		private string _Age;
		private string _Agename;
		private string _TypeName;
		private string _SickType;
		private string _DeptName;
		private string _DeptCode;
		private string _ParItemNo;
		private string _PartName;
		private int? _ItemNo;
		private string _ItemName;
		private string _ReportValue;
		private string _Unit;
		private string _RefRange;
		private string _ResultStatus;
		private string _Technician;
		private string _Checker;
		private DateTime? _CheckDate;
		private int? _OrderBy;

		///// <summary>
		///// 
		///// </summary>
		//[Field("blhjzh")]
		//public string blhjzh
		//{
		//	get { return _blhjzh; }
		//	set
		//	{
		//		this.OnPropertyValueChange("blhjzh");
		//		this._blhjzh = value;
		//	}
		//}
		///// <summary>
		///// 
		///// </summary>
		//[Field("HISXMNO")]
		//public string HISXMNO
		//{
		//	get { return _HISXMNO; }
		//	set
		//	{
		//		this.OnPropertyValueChange("HISXMNO");
		//		this._HISXMNO = value;
		//	}
		//}
		///// <summary>
		///// 
		///// </summary>
		//[Field("XMMC")]
		//public string XMMC
		//{
		//	get { return _XMMC; }
		//	set
		//	{
		//		this.OnPropertyValueChange("XMMC");
		//		this._XMMC = value;
		//	}
		//}
		///// <summary>
		///// 
		///// </summary>
		//[Field("xmno")]
		//public int? xmno
		//{
		//	get { return _xmno; }
		//	set
		//	{
		//		this.OnPropertyValueChange("xmno");
		//		this._xmno = value;
		//	}
		//}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReceiveDate")]
		public DateTime? ReceiveDate
		{
			get { return _ReceiveDate; }
			set
			{
				this.OnPropertyValueChange("ReceiveDate");
				this._ReceiveDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IDCard")]
		public string IDCard
		{
			get { return _IDCard; }
			set
			{
				this.OnPropertyValueChange("IDCard");
				this._IDCard = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PatNo")]
		public string PatNo
		{
			get { return _PatNo; }
			set
			{
				this.OnPropertyValueChange("PatNo");
				this._PatNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Cname")]
		public string Cname
		{
			get { return _Cname; }
			set
			{
				this.OnPropertyValueChange("Cname");
				this._Cname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Age")]
		public string Age
		{
			get { return _Age; }
			set
			{
				this.OnPropertyValueChange("Age");
				this._Age = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Agename")]
		public string Agename
		{
			get { return _Agename; }
			set
			{
				this.OnPropertyValueChange("Agename");
				this._Agename = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TypeName")]
		public string TypeName
		{
			get { return _TypeName; }
			set
			{
				this.OnPropertyValueChange("TypeName");
				this._TypeName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SickType")]
		public string SickType
		{
			get { return _SickType; }
			set
			{
				this.OnPropertyValueChange("SickType");
				this._SickType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptName")]
		public string DeptName
		{
			get { return _DeptName; }
			set
			{
				this.OnPropertyValueChange("DeptName");
				this._DeptName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptCode")]
		public string DeptCode
		{
			get { return _DeptCode; }
			set
			{
				this.OnPropertyValueChange("DeptCode");
				this._DeptCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParItemNo")]
		public string ParItemNo
		{
			get { return _ParItemNo; }
			set
			{
				this.OnPropertyValueChange("ParItemNo");
				this._ParItemNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PartName")]
		public string PartName
		{
			get { return _PartName; }
			set
			{
				this.OnPropertyValueChange("PartName");
				this._PartName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ItemNo")]
		public int? ItemNo
		{
			get { return _ItemNo; }
			set
			{
				this.OnPropertyValueChange("ItemNo");
				this._ItemNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ItemName")]
		public string ItemName
		{
			get { return _ItemName; }
			set
			{
				this.OnPropertyValueChange("ItemName");
				this._ItemName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReportValue")]
		public string ReportValue
		{
			get { return _ReportValue; }
			set
			{
				this.OnPropertyValueChange("ReportValue");
				this._ReportValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Unit")]
		public string Unit
		{
			get { return _Unit; }
			set
			{
				this.OnPropertyValueChange("Unit");
				this._Unit = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RefRange")]
		public string RefRange
		{
			get { return _RefRange; }
			set
			{
				this.OnPropertyValueChange("RefRange");
				this._RefRange = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ResultStatus")]
		public string ResultStatus
		{
			get { return _ResultStatus; }
			set
			{
				this.OnPropertyValueChange("ResultStatus");
				this._ResultStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Technician")]
		public string Technician
		{
			get { return _Technician; }
			set
			{
				this.OnPropertyValueChange("Technician");
				this._Technician = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Checker")]
		public string Checker
		{
			get { return _Checker; }
			set
			{
				this.OnPropertyValueChange("Checker");
				this._Checker = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CheckDate")]
		public DateTime? CheckDate
		{
			get { return _CheckDate; }
			set
			{
				this.OnPropertyValueChange("CheckDate");
				this._CheckDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OrderBy")]
		public int? OrderBy
		{
			get { return _OrderBy; }
			set
			{
				this.OnPropertyValueChange("OrderBy");
				this._OrderBy = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				//_.blhjzh,
				//_.HISXMNO,
				//_.XMMC,
				//_.xmno,
				_.ReceiveDate,
				_.IDCard,
				_.PatNo,
				_.Cname,
				_.Age,
				_.Agename,
				_.TypeName,
				_.SickType,
				_.DeptName,
				_.DeptCode,
				_.ParItemNo,
				_.PartName,
				_.ItemNo,
				_.ItemName,
				_.ReportValue,
				_.Unit,
				_.RefRange,
				_.ResultStatus,
				_.Technician,
				_.Checker,
				_.CheckDate,
				_.OrderBy,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				//this._blhjzh,
				//this._HISXMNO,
				//this._XMMC,
				//this._xmno,
				this._ReceiveDate,
				this._IDCard,
				this._PatNo,
				this._Cname,
				this._Age,
				this._Agename,
				this._TypeName,
				this._SickType,
				this._DeptName,
				this._DeptCode,
				this._ParItemNo,
				this._PartName,
				this._ItemNo,
				this._ItemName,
				this._ReportValue,
				this._Unit,
				this._RefRange,
				this._ResultStatus,
				this._Technician,
				this._Checker,
				this._CheckDate,
				this._OrderBy,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			///// <summary>
			///// * 
			///// </summary>
			//public readonly static Field All = new Field("*", "IView_HIS_LISResult");
			///// <summary>
			///// 
			///// </summary>
			//public readonly static Field blhjzh = new Field("blhjzh", "IView_HIS_LISResult", "");
			///// <summary>
			///// 
			///// </summary>
			//public readonly static Field HISXMNO = new Field("HISXMNO", "IView_HIS_LISResult", "");
			///// <summary>
			///// 
			///// </summary>
			//public readonly static Field XMMC = new Field("XMMC", "IView_HIS_LISResult", "");
			///// <summary>
			///// 
			///// </summary>
			//public readonly static Field xmno = new Field("xmno", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReceiveDate = new Field("ReceiveDate", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IDCard = new Field("IDCard", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PatNo = new Field("PatNo", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Cname = new Field("Cname", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Age = new Field("Age", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Agename = new Field("Agename", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TypeName = new Field("TypeName", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SickType = new Field("SickType", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParItemNo = new Field("ParItemNo", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PartName = new Field("PartName", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ItemNo = new Field("ItemNo", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ItemName = new Field("ItemName", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReportValue = new Field("ReportValue", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Unit = new Field("Unit", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RefRange = new Field("RefRange", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ResultStatus = new Field("ResultStatus", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Technician = new Field("Technician", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Checker = new Field("Checker", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CheckDate = new Field("CheckDate", "IView_HIS_LISResult", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderBy = new Field("OrderBy", "IView_HIS_LISResult", "");
		}
        #endregion

    }
}