//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类IView_HIS_Outpatients 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_HIS_Outpatients")]
    [Serializable]
    public partial class IView_HIS_Outpatients : Entity
    {
        #region Model
        private DateTime _RegisterTime;
        private string _OutpatientNo;
        private string _PatientID;
        private string _PatientName;
        private string _Sex;
        private string _Birthday;
        private string _Age;
        private string _DeptCode;
        private string _DeptName;
        private string _DoctorNo;
        private string _DoctorName;
        private int? _RegisterNo;
        private string _PatientAddress;
        private string _ContactNumber;
        private string _Category;
        private string _EmerencyFlag;
        private string _PayType;
        private string _PayTypeCode;
        private string _CardNo;
        private string _SearchCode;
        private string _IDCard;
        private string _Address;
        private string _State;
        /// <summary>
        /// 
        /// </summary>
        public DateTime RegisterTime
        {
            get { return _RegisterTime; }
            set
            {
                this.OnPropertyValueChange(_.RegisterTime, _RegisterTime, value);
                this._RegisterTime = value;
            }
        }

        public string PayTypeCode
        {
            get { return _PayTypeCode; }
            set
            {
                this.OnPropertyValueChange(_.PayTypeCode, _PayTypeCode, value);
                this._PayTypeCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OutpatientNo
        {
            get { return _OutpatientNo; }
            set
            {
                this.OnPropertyValueChange(_.OutpatientNo, _OutpatientNo, value);
                this._OutpatientNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PatientID
        {
            get { return _PatientID; }
            set
            {
                this.OnPropertyValueChange(_.PatientID, _PatientID, value);
                this._PatientID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PatientName
        {
            get { return _PatientName; }
            set
            {
                this.OnPropertyValueChange(_.PatientName, _PatientName, value);
                this._PatientName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Sex
        {
            get { return _Sex; }
            set
            {
                this.OnPropertyValueChange(_.SEX, _Sex, value);
                this._Sex = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Birthday
        {
            get { return _Birthday; }
            set
            {
                this.OnPropertyValueChange(_.Birthday, _Birthday, value);
                this._Birthday = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Age
        {
            get { return _Age; }
            set
            {
                this.OnPropertyValueChange(_.Age, _Age, value);
                this._Age = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DeptCode
        {
            get { return _DeptCode; }
            set
            {
                this.OnPropertyValueChange(_.DeptCode, _DeptCode, value);
                this._DeptCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DeptName
        {
            get { return _DeptName; }
            set
            {
                this.OnPropertyValueChange(_.DeptName, _DeptName, value);
                this._DeptName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DoctorNo
        {
            get { return _DoctorNo; }
            set
            {
                this.OnPropertyValueChange(_.DoctorNo, _DoctorNo, value);
                this._DoctorNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DoctorName
        {
            get { return _DoctorName; }
            set
            {
                this.OnPropertyValueChange(_.DoctorName, _DoctorName, value);
                this._DoctorName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? RegisterNo
        {
            get { return _RegisterNo; }
            set
            {
                this.OnPropertyValueChange(_.RegisterNo, _RegisterNo, value);
                this._RegisterNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PatientAddress
        {
            get { return _PatientAddress; }
            set
            {
                this.OnPropertyValueChange(_.PatientAddress, _PatientAddress, value);
                this._PatientAddress = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ContactNumber
        {
            get { return _ContactNumber; }
            set
            {
                this.OnPropertyValueChange(_.ContactNumber, _ContactNumber, value);
                this._ContactNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Category
        {
            get { return _Category; }
            set
            {
                this.OnPropertyValueChange(_.Category, _Category, value);
                this._Category = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EmerencyFlag
        {
            get { return _EmerencyFlag; }
            set
            {
                this.OnPropertyValueChange(_.EmerencyFlag, _EmerencyFlag, value);
                this._EmerencyFlag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PayType
        {
            get { return _PayType; }
            set
            {
                this.OnPropertyValueChange(_.PayType, _PayType, value);
                this._PayType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CardNo
        {
            get { return _CardNo; }
            set
            {
                this.OnPropertyValueChange(_.CardNo, _CardNo, value);
                this._CardNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SearchCode
        {
            get { return _SearchCode; }
            set
            {
                this.OnPropertyValueChange(_.SearchCode, _SearchCode, value);
                this._SearchCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string IDCard
        {
            get { return _IDCard; }
            set
            {
                this.OnPropertyValueChange(_.IDCard, _IDCard, value);
                this._IDCard = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Address
        {
            get { return _Address; }
            set
            {
                this.OnPropertyValueChange(_.Address, _Address, value);
                this._Address = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string State
        {
            get { return _State; }
            set
            {
                this.OnPropertyValueChange(_.State, _State, value);
                this._State = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 是否只读
        /// </summary>
        public override bool IsReadOnly()
        {
            return true;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.RegisterTime,
				_.OutpatientNo,
				_.PatientID,
				_.PatientName,
				_.SEX,
				_.Birthday,
				_.Age,
				_.DeptCode,
				_.DeptName,
				_.DoctorNo,
				_.DoctorName,
				_.RegisterNo,
				_.PatientAddress,
				_.ContactNumber,
				_.Category,
				_.EmerencyFlag,
				_.PayType,
				_.CardNo,
				_.SearchCode,
				_.IDCard,
				_.Address,
				_.State,
            _.PayTypeCode};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._RegisterTime,
				this._OutpatientNo,
				this._PatientID,
				this._PatientName,
				this._Sex,
				this._Birthday,
				this._Age,
				this._DeptCode,
				this._DeptName,
				this._DoctorNo,
				this._DoctorName,
				this._RegisterNo,
				this._PatientAddress,
				this._ContactNumber,
				this._Category,
				this._EmerencyFlag,
				this._PayType,
				this._CardNo,
				this._SearchCode,
				this._IDCard,
				this._Address,
				this._State,
            this._PayTypeCode};
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "IView_HIS_Outpatients");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RegisterTime = new Field("RegisterTime", "IView_HIS_Outpatients", "RegisterTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OutpatientNo = new Field("OutpatientNo", "IView_HIS_Outpatients", "OutpatientNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PatientID = new Field("PatientID", "IView_HIS_Outpatients", "PatientID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PatientName = new Field("PatientName", "IView_HIS_Outpatients", "PatientName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SEX = new Field("SEX", "IView_HIS_Outpatients", "SEX");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Birthday = new Field("Birthday", "IView_HIS_Outpatients", "Birthday");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Age = new Field("Age", "IView_HIS_Outpatients", "Age");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DeptCode = new Field("DeptCode", "IView_HIS_Outpatients", "DeptCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DeptName = new Field("DeptName", "IView_HIS_Outpatients", "DeptName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DoctorNo = new Field("DoctorNo", "IView_HIS_Outpatients", "DoctorNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DoctorName = new Field("DoctorName", "IView_HIS_Outpatients", "DoctorName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RegisterNo = new Field("RegisterNo", "IView_HIS_Outpatients", "RegisterNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PatientAddress = new Field("PatientAddress", "IView_HIS_Outpatients", "PatientAddress");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ContactNumber = new Field("ContactNumber", "IView_HIS_Outpatients", "ContactNumber");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Category = new Field("Category", "IView_HIS_Outpatients", "Category");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field EmerencyFlag = new Field("EmerencyFlag", "IView_HIS_Outpatients", "EmerencyFlag");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PayType = new Field("PayType", "IView_HIS_Outpatients", "PayType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CardNo = new Field("CardNo", "IView_HIS_Outpatients", "CardNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SearchCode = new Field("SearchCode", "IView_HIS_Outpatients", "SearchCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IDCard = new Field("IDCard", "IView_HIS_Outpatients", "IDCard");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Address = new Field("Address", "IView_HIS_Outpatients", "Address");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field State = new Field("State", "IView_HIS_Outpatients", "State");

            public readonly static Field PayTypeCode = new Field("PayTypeCode", "IView_HIS_Outpatients", "PayTypeCode");
            

        }
        #endregion


    }
}

