//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类IView_User。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_User")]
    [Serializable]
    public partial class IView_User : Entity
    {
        #region Model
        private string _ID;
        private string _Code;
        private string _Sex;
        private string _Name;
        private string _Dept_Code;
        private int _Status;
        private string _Type;
        private string _Pwd;
        private string _JobTitle;
        private string _JobTitleCode;
        private string _JobTitleName;
        private string _SearchCode;
        private string _DoctorPhone;
        private byte[] _NameImage;
        private string _HealthCareCode;
        private string _IDCard;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Code")]
        public string Code
        {
            get { return _Code; }
            set
            {
                this.OnPropertyValueChange("Code");
                this._Code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Sex")]
        public string Sex
        {
            get { return _Sex; }
            set
            {
                this.OnPropertyValueChange("Sex");
                this._Sex = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Name")]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Dept_Code")]
        public string Dept_Code
        {
            get { return _Dept_Code; }
            set
            {
                this.OnPropertyValueChange("Dept_Code");
                this._Dept_Code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Status")]
        public int Status
        {
            get { return _Status; }
            set
            {
                this.OnPropertyValueChange("Status");
                this._Status = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Type")]
        public string Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Pwd")]
        public string Pwd
        {
            get { return _Pwd; }
            set
            {
                this.OnPropertyValueChange("Pwd");
                this._Pwd = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("JobTitle")]
        public string JobTitle
        {
            get { return _JobTitle; }
            set
            {
                this.OnPropertyValueChange("JobTitle");
                this._JobTitle = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("JobTitleCode")]
        public string JobTitleCode
        {
            get { return _JobTitleCode; }
            set
            {
                this.OnPropertyValueChange("JobTitleCode");
                this._JobTitleCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("JobTitleName")]
        public string JobTitleName
        {
            get { return _JobTitleName; }
            set
            {
                this.OnPropertyValueChange("JobTitleName");
                this._JobTitleName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SearchCode")]
        public string SearchCode
        {
            get { return _SearchCode; }
            set
            {
                this.OnPropertyValueChange("SearchCode");
                this._SearchCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DoctorPhone")]
        public string DoctorPhone
        {
            get { return _DoctorPhone; }
            set
            {
                this.OnPropertyValueChange("DoctorPhone");
                this._DoctorPhone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("NameImage")]
        public byte[] NameImage
        {
            get { return _NameImage; }
            set
            {
                this.OnPropertyValueChange("NameImage");
                this._NameImage = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("HealthCareCode")]
        public string HealthCareCode
        {
            get { return _HealthCareCode; }
            set
            {
                this.OnPropertyValueChange("HealthCareCode");
                this._HealthCareCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("IDCard")]
        public string IDCard
        {
            get { return _IDCard; }
            set
            {
                this.OnPropertyValueChange("IDCard");
                this._IDCard = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.Code,
                _.Sex,
                _.Name,
                _.Dept_Code,
                _.Status,
                _.Type,
                _.Pwd,
                _.JobTitle,
                _.JobTitleCode,
                _.JobTitleName,
                _.SearchCode,
                _.DoctorPhone,
                _.NameImage,
                _.HealthCareCode,
                _.IDCard
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._Code,
                this._Sex,
                this._Name,
                this._Dept_Code,
                this._Status,
                this._Type,
                this._Pwd,
                this._JobTitle,
                this._JobTitleCode,
                this._JobTitleName,
                this._SearchCode,
                this._DoctorPhone,
                this._NameImage,
                this._HealthCareCode,
                this._IDCard
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "IView_User");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Dept_Code = new Field("Dept_Code", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Status = new Field("Status", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Pwd = new Field("Pwd", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field JobTitle = new Field("JobTitle", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field JobTitleCode = new Field("JobTitleCode", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field JobTitleName = new Field("JobTitleName", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorPhone = new Field("DoctorPhone", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NameImage = new Field("NameImage", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HealthCareCode = new Field("HealthCareCode", "IView_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IDCard = new Field("IDCard", "IView_User", "");
        }
        #endregion
    }
}