//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类IView_HIS_DrugUsage 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("IView_HIS_DrugUsage")]
    [Serializable]
    public partial class IView_HIS_DrugUsage : Entity
    {
        #region Model
        private string _Code;
        private string _Name;
        private int? _Number;
        private string _Type;
        private string _SearchCode;
        /// <summary>
        /// 
        /// </summary>
        public string Code
        {
            get { return _Code; }
            set
            {
                this.OnPropertyValueChange(_.Code, _Code, value);
                this._Code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange(_.Name, _Name, value);
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Number
        {
            get { return _Number; }
            set
            {
                this.OnPropertyValueChange(_.Number, _Number, value);
                this._Number = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange(_.Type, _Type, value);
                this._Type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SearchCode
        {
            get { return _SearchCode; }
            set
            {
                this.OnPropertyValueChange(_.SearchCode, _SearchCode, value);
                this._SearchCode = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 是否只读
        /// </summary>
        public override bool IsReadOnly()
        {
            return true;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Code,
				_.Name,
				_.Number,
				_.Type,
            _.SearchCode};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Code,
				this._Name,
				this._Number,
				this._Type,
            this._SearchCode};
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "IView_HIS_DrugUsage");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Code = new Field("Code", "IView_HIS_DrugUsage", "Code");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Name = new Field("Name", "IView_HIS_DrugUsage", "Name");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Number = new Field("Number", "IView_HIS_DrugUsage", "Number");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Type = new Field("Type", "IView_HIS_DrugUsage", "Type");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SearchCode = new Field("SearchCode", "IView_HIS_DrugUsage", "SearchCode");
        }
        #endregion


    }
}

