//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace CIS.Model
{

	/// <summary>
	/// 实体类OP_Dic_ReportDataSource 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("OP_Dic_ReportDataSource")]
	[Serializable]
	public partial class OP_Dic_ReportDataSource : Entity 
	{
		#region Model
		private string _ElementCode;
		private string _ElementName;
		private int? _Index;
		/// <summary>
		/// 
		/// </summary>
		public string ElementCode
		{
			get{ return _ElementCode; }
			set
			{
				this.OnPropertyValueChange(_.ElementCode,_ElementCode,value);
				this._ElementCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ElementName
		{
			get{ return _ElementName; }
			set
			{
				this.OnPropertyValueChange(_.ElementName,_ElementName,value);
				this._ElementName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Index
		{
			get{ return _Index; }
			set
			{
				this.OnPropertyValueChange(_.Index,_Index,value);
				this._Index=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ElementCode};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ElementCode,
				_.ElementName,
				_.Index};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ElementCode,
				this._ElementName,
				this._Index};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","OP_Dic_ReportDataSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ElementCode = new Field("ElementCode","OP_Dic_ReportDataSource","ElementCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ElementName = new Field("ElementName","OP_Dic_ReportDataSource","ElementName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Index = new Field("Index","OP_Dic_ReportDataSource","Index");
		}
		#endregion


	}
}

