//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类OP_DiagnosisReport。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_DiagnosisReport")]
    [Serializable]
    public partial class OP_DiagnosisReport : Entity
    {
        #region Model
        private string _ID;
        private string _Content;
        private string _DoctorID;
        private string _DeptCode;
        private string _DoctorName;
        private string _DeptName;
        private string _TreatmentNo;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Content")]
        public string Content
        {
            get { return _Content; }
            set
            {
                this.OnPropertyValueChange("Content");
                this._Content = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DoctorID")]
        public string DoctorID
        {
            get { return _DoctorID; }
            set
            {
                this.OnPropertyValueChange("DoctorID");
                this._DoctorID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeptCode")]
        public string DeptCode
        {
            get { return _DeptCode; }
            set
            {
                this.OnPropertyValueChange("DeptCode");
                this._DeptCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DoctorName")]
        public string DoctorName
        {
            get { return _DoctorName; }
            set
            {
                this.OnPropertyValueChange("DoctorName");
                this._DoctorName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeptName")]
        public string DeptName
        {
            get { return _DeptName; }
            set
            {
                this.OnPropertyValueChange("DeptName");
                this._DeptName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TreatmentNo")]
        public string TreatmentNo
        {
            get { return _TreatmentNo; }
            set
            {
                this.OnPropertyValueChange("TreatmentNo");
                this._TreatmentNo = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.Content,
                _.DoctorID,
                _.DeptCode,
                _.DoctorName,
                _.DeptName,
                _.TreatmentNo,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._Content,
                this._DoctorID,
                this._DeptCode,
                this._DoctorName,
                this._DeptName,
                this._TreatmentNo,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "OP_HospitalizedReport");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "OP_HospitalizedReport", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Content = new Field("Content", "OP_HospitalizedReport", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DoctorID = new Field("DoctorID", "OP_HospitalizedReport", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DeptCode = new Field("DeptCode", "OP_HospitalizedReport", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DoctorName = new Field("DoctorName", "OP_HospitalizedReport", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DeptName = new Field("DeptName", "OP_HospitalizedReport", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field TreatmentNo = new Field("TreatmentNo", "OP_HospitalizedReport", "");
        }
        #endregion
    }
}