//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类OP_DrugGroup_Detail。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_DrugGroup_Detail")]
    [Serializable]
    public partial class OP_DrugGroup_Detail : Entity
    {
        #region Model
        private string _ID;
        private string _DrugID;
        private string _GroupID;
        private decimal? _Amount;
        private string _DosageUnit;
        private string _Usage;
        private string _Frequency;
        private string _Owner;
        private int? _No;
        private int? _Num;
        private int? _Days;
        private string _DrugDept;
        private string _GroupNo;

        /// <summary>
        /// ID
        /// </summary>
        [Field("ID")]
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 药品ID
        /// </summary>
        [Field("DrugID")]
        public string DrugID
        {
            get { return _DrugID; }
            set
            {
                this.OnPropertyValueChange("DrugID");
                this._DrugID = value;
            }
        }
        /// <summary>
        /// 组套ID
        /// </summary>
        [Field("GroupID")]
        public string GroupID
        {
            get { return _GroupID; }
            set
            {
                this.OnPropertyValueChange("GroupID");
                this._GroupID = value;
            }
        }
        /// <summary>
        /// 单次用量
        /// </summary>
        [Field("Amount")]
        public decimal? Amount
        {
            get { return _Amount; }
            set
            {
                this.OnPropertyValueChange("Amount");
                this._Amount = value;
            }
        }
        /// <summary>
        /// 单次用量单位
        /// </summary>
        [Field("DosageUnit")]
        public string DosageUnit
        {
            get { return _DosageUnit; }
            set
            {
                this.OnPropertyValueChange("DosageUnit");
                this._DosageUnit = value;
            }
        }
        /// <summary>
        /// 用法（给药途径）
        /// </summary>
        [Field("Usage")]
        public string Usage
        {
            get { return _Usage; }
            set
            {
                this.OnPropertyValueChange("Usage");
                this._Usage = value;
            }
        }
        /// <summary>
        /// 频率（用药间隔）
        /// </summary>
        [Field("Frequency")]
        public string Frequency
        {
            get { return _Frequency; }
            set
            {
                this.OnPropertyValueChange("Frequency");
                this._Frequency = value;
            }
        }
        /// <summary>
        /// 拥有者（方便查询）
        /// </summary>
        [Field("Owner")]
        public string Owner
        {
            get { return _Owner; }
            set
            {
                this.OnPropertyValueChange("Owner");
                this._Owner = value;
            }
        }
        /// <summary>
        /// 序号
        /// </summary>
        [Field("No")]
        public int? No
        {
            get { return _No; }
            set
            {
                this.OnPropertyValueChange("No");
                this._No = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Num")]
        public int? Num
        {
            get { return _Num; }
            set
            {
                this.OnPropertyValueChange("Num");
                this._Num = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Days")]
        public int? Days
        {
            get { return _Days; }
            set
            {
                this.OnPropertyValueChange("Days");
                this._Days = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DrugDept")]
        public string DrugDept
        {
            get { return _DrugDept; }
            set
            {
                this.OnPropertyValueChange("DrugDept");
                this._DrugDept = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("GroupNo")]
        public string GroupNo
        {
            get { return _GroupNo; }
            set
            {
                this.OnPropertyValueChange("GroupNo");
                this._GroupNo = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.DrugID,
				_.GroupID,
				_.Amount,
				_.DosageUnit,
				_.Usage,
				_.Frequency,
				_.Owner,
				_.No,
				_.Num,
				_.Days,
				_.DrugDept,
				_.GroupNo,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._DrugID,
				this._GroupID,
				this._Amount,
				this._DosageUnit,
				this._Usage,
				this._Frequency,
				this._Owner,
				this._No,
				this._Num,
				this._Days,
				this._DrugDept,
				this._GroupNo,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "OP_DrugGroup_Detail");
            /// <summary>
            /// ID
            /// </summary>
            public readonly static Field ID = new Field("ID", "OP_DrugGroup_Detail", "ID");
            /// <summary>
            /// 药品ID
            /// </summary>
            public readonly static Field DrugID = new Field("DrugID", "OP_DrugGroup_Detail", "药品ID");
            /// <summary>
            /// 组套ID
            /// </summary>
            public readonly static Field GroupID = new Field("GroupID", "OP_DrugGroup_Detail", "组套ID");
            /// <summary>
            /// 单次用量
            /// </summary>
            public readonly static Field Amount = new Field("Amount", "OP_DrugGroup_Detail", "单次用量");
            /// <summary>
            /// 单次用量单位
            /// </summary>
            public readonly static Field DosageUnit = new Field("DosageUnit", "OP_DrugGroup_Detail", "单次用量单位");
            /// <summary>
            /// 用法（给药途径）
            /// </summary>
            public readonly static Field Usage = new Field("Usage", "OP_DrugGroup_Detail", "用法（给药途径）");
            /// <summary>
            /// 频率（用药间隔）
            /// </summary>
            public readonly static Field Frequency = new Field("Frequency", "OP_DrugGroup_Detail", "频率（用药间隔）");
            /// <summary>
            /// 拥有者（方便查询）
            /// </summary>
            public readonly static Field Owner = new Field("Owner", "OP_DrugGroup_Detail", "拥有者（方便查询）");
            /// <summary>
            /// 序号
            /// </summary>
            public readonly static Field No = new Field("No", "OP_DrugGroup_Detail", "序号");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Num = new Field("Num", "OP_DrugGroup_Detail", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Days = new Field("Days", "OP_DrugGroup_Detail", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field DrugDept = new Field("DrugDept", "OP_DrugGroup_Detail", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field GroupNo = new Field("GroupNo", "OP_DrugGroup_Detail", "");
        }
        #endregion
    }
}