//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类OP_Dic_DrugPermission。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_Dic_DrugPermission")]
    [Serializable]
    public partial class OP_Dic_DrugPermission : Entity
    {
        #region Model
        private string _ID;
        private string _DrugID;
        private string _DoctorCode;
        private string _TitleName;
        private string _DeptCode;
        private int? _Flag;
        private DateTime? _UpdateTime;
        private int? _DoctorNumber;
        private string _DoctorNumberInterval;
        private int? _PatientNumber;
        private string _PatientNumberInterval;
        private DrugLimitPrescriptionTypeEnum _PrescriptionType;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DrugID")]
        public string DrugID
        {
            get { return _DrugID; }
            set
            {
                this.OnPropertyValueChange("DrugID");
                this._DrugID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DoctorCode")]
        public string DoctorCode
        {
            get { return _DoctorCode; }
            set
            {
                this.OnPropertyValueChange("DoctorCode");
                this._DoctorCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TitleName")]
        public string TitleName
        {
            get { return _TitleName; }
            set
            {
                this.OnPropertyValueChange("TitleName");
                this._TitleName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeptCode")]
        public string DeptCode
        {
            get { return _DeptCode; }
            set
            {
                this.OnPropertyValueChange("DeptCode");
                this._DeptCode = value;
            }
        }
        /// <summary>
        /// _0表示允许  1表示限制
        /// </summary>
        [Field("Flag")]
        public int? Flag
        {
            get { return _Flag; }
            set
            {
                this.OnPropertyValueChange("Flag");
                this._Flag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UpdateTime")]
        public DateTime? UpdateTime
        {
            get { return _UpdateTime; }
            set
            {
                this.OnPropertyValueChange("UpdateTime");
                this._UpdateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DoctorNumber")]
        public int? DoctorNumber
        {
            get { return _DoctorNumber; }
            set
            {
                this.OnPropertyValueChange("DoctorNumber");
                this._DoctorNumber = value;
            }
        }
        /// <summary>
        /// 数量间隔时间 月或日
        /// </summary>
        [Field("DoctorNumberInterval")]
        public string DoctorNumberInterval
        {
            get { return _DoctorNumberInterval; }
            set
            {
                this.OnPropertyValueChange("DoctorNumberInterval");
                this._DoctorNumberInterval = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PatientNumber")]
        public int? PatientNumber
        {
            get { return _PatientNumber; }
            set
            {
                this.OnPropertyValueChange("PatientNumber");
                this._PatientNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PatientNumberInterval")]
        public string PatientNumberInterval
        {
            get { return _PatientNumberInterval; }
            set
            {
                this.OnPropertyValueChange("PatientNumberInterval");
                this._PatientNumberInterval = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PrescriptionType")]
        public DrugLimitPrescriptionTypeEnum PrescriptionType
        {
            get { return _PrescriptionType; }
            set
            {
                this.OnPropertyValueChange("PrescriptionType");
                this._PrescriptionType = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.DrugID,
                _.DoctorCode,
                _.TitleName,
                _.DeptCode,
                _.Flag,
                _.UpdateTime,
                _.DoctorNumber,
                _.DoctorNumberInterval,
                _.PatientNumber,
                _.PatientNumberInterval,
                _.PrescriptionType
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._DrugID,
                this._DoctorCode,
                this._TitleName,
                this._DeptCode,
                this._Flag,
                this._UpdateTime,
                this._DoctorNumber,
                this._DoctorNumberInterval,
                this._PatientNumber,
                this._PatientNumberInterval,
                this._PrescriptionType
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "OP_Dic_DrugPermission");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DrugID = new Field("DrugID", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorCode = new Field("DoctorCode", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TitleName = new Field("TitleName", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// _0表示允许  1表示限制
			/// </summary>
			public readonly static Field Flag = new Field("Flag", "OP_Dic_DrugPermission", "_0表示允许  1表示限制");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorNumber = new Field("DoctorNumber", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// 数量间隔时间 月或日
			/// </summary>
			public readonly static Field DoctorNumberInterval = new Field("DoctorNumberInterval", "OP_Dic_DrugPermission", "数量间隔时间 月或日");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientNumber = new Field("PatientNumber", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientNumberInterval = new Field("PatientNumberInterval", "OP_Dic_DrugPermission", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PrescriptionType = new Field("PrescriptionType", "OP_Dic_DrugPermission", "");
        }
        #endregion
    }
}