//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类OP_InfectionReport 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_InfectionReport")]
	[Serializable]
	public partial class OP_InfectionReport : Entity 
	{
		#region Model
		private string _ID;
		private object _XMLDocument;
		private string _DeptCode;
		private string _DeptName;
		private string _DoctorCode;
		private string _DoctorName;
		private string _PatientID;
		private string _PatientName;
		private DateTime? _UpdateTime;
		/// <summary>
		/// 
		/// </summary>
		public string ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public object XMLDocument
		{
			get{ return _XMLDocument; }
			set
			{
				this.OnPropertyValueChange(_.XMLDocument,_XMLDocument,value);
				this._XMLDocument=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange(_.DeptCode,_DeptCode,value);
				this._DeptCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DeptName
		{
			get{ return _DeptName; }
			set
			{
				this.OnPropertyValueChange(_.DeptName,_DeptName,value);
				this._DeptName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DoctorCode
		{
			get{ return _DoctorCode; }
			set
			{
				this.OnPropertyValueChange(_.DoctorCode,_DoctorCode,value);
				this._DoctorCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DoctorName
		{
			get{ return _DoctorName; }
			set
			{
				this.OnPropertyValueChange(_.DoctorName,_DoctorName,value);
				this._DoctorName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PatientID
		{
			get{ return _PatientID; }
			set
			{
				this.OnPropertyValueChange(_.PatientID,_PatientID,value);
				this._PatientID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PatientName
		{
			get{ return _PatientName; }
			set
			{
				this.OnPropertyValueChange(_.PatientName,_PatientName,value);
				this._PatientName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.XMLDocument,
				_.DeptCode,
				_.DeptName,
				_.DoctorCode,
				_.DoctorName,
				_.PatientID,
				_.PatientName,
				_.UpdateTime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._XMLDocument,
				this._DeptCode,
				this._DeptName,
				this._DoctorCode,
				this._DoctorName,
				this._PatientID,
				this._PatientName,
				this._UpdateTime};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","OP_InfectionReport");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","OP_InfectionReport","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XMLDocument = new Field("XMLDocument","OP_InfectionReport","XMLDocument");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode","OP_InfectionReport","DeptCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName","OP_InfectionReport","DeptName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorCode = new Field("DoctorCode","OP_InfectionReport","DoctorCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorName = new Field("DoctorName","OP_InfectionReport","DoctorName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientID = new Field("PatientID","OP_InfectionReport","PatientID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientName = new Field("PatientName","OP_InfectionReport","PatientName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","OP_InfectionReport","UpdateTime");
		}
		#endregion


	}
}

