//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类OP_Prescription 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_Prescription")]
    [Serializable]
    public partial class OP_Prescription : Entity
    {
        #region Model
        private string _ID;
        private string _TreatmentNo;
        private string _PatientID;
        private string _PatientName;
        private string _PrescriptionNo;
        private int? _RecordNumber;
        private string _PrescriptionType;
        private string _Explanation;
        private string _ConditionSummary;
        private string _Specimen;
        private string _Burette;
        private string _Parts;
        private string _DeptCode;
        private string _UserID;
        private DateTime? _UpdateTime;
        private int? _Status;
        private int? _IsExpedited;
        private int? _HerbalMedicineNum;
        private string _DiagnosisName;
        private string _IDCard;
        private string _DoctorPhone;
        private string _PayType;
        private string _UserName;
        private string _Sex;
        private string _Age;
        private int _HISInterface_PrescriptionNo;
        private string _CardNo;
        private string _HerbsGroupName;
        private string _PrescriptionCirculation_PrescriptionNo;

        /// <summary>
        /// ID
        /// </summary>
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange(_.ID, _ID, value);
                this._ID = value;
            }
        }
        /// <summary>
        /// 就诊号
        /// </summary>
        public string TreatmentNo
        {
            get { return _TreatmentNo; }
            set
            {
                this.OnPropertyValueChange(_.TreatmentNo, _TreatmentNo, value);
                this._TreatmentNo = value;
            }
        }
        /// <summary>
        /// 患者ID
        /// </summary>
        public string PatientID
        {
            get { return _PatientID; }
            set
            {
                this.OnPropertyValueChange(_.PatientID, _PatientID, value);
                this._PatientID = value;
            }
        }
        /// <summary>
        /// 患者姓名
        /// </summary>
        public string PatientName
        {
            get { return _PatientName; }
            set
            {
                this.OnPropertyValueChange(_.PatientName, _PatientName, value);
                this._PatientName = value;
            }
        }
        /// <summary>
        /// 处方编号
        /// </summary>
        public string PrescriptionNo
        {
            get { return _PrescriptionNo; }
            set
            {
                this.OnPropertyValueChange(_.PrescriptionNo, _PrescriptionNo, value);
                this._PrescriptionNo = value;
            }
        }
        /// <summary>
        /// 记录数量
        /// </summary>
        public int? RecordNumber
        {
            get { return _RecordNumber; }
            set
            {
                this.OnPropertyValueChange(_.RecordNumber, _RecordNumber, value);
                this._RecordNumber = value;
            }
        }
        /// <summary>
        /// 处方类别
        /// </summary>
        public string PrescriptionType
        {
            get { return _PrescriptionType; }
            set
            {
                this.OnPropertyValueChange(_.PrescriptionType, _PrescriptionType, value);
                this._PrescriptionType = value;
            }
        }
        /// <summary>
        /// 医生说明
        /// </summary>
        public string Explanation
        {
            get { return _Explanation; }
            set
            {
                this.OnPropertyValueChange(_.Explanation, _Explanation, value);
                this._Explanation = value;
            }
        }
        /// <summary>
        /// 病史摘要
        /// </summary>
        public string ConditionSummary
        {
            get { return _ConditionSummary; }
            set
            {
                this.OnPropertyValueChange(_.ConditionSummary, _ConditionSummary, value);
                this._ConditionSummary = value;
            }
        }
        /// <summary>
        /// 标本
        /// </summary>
        public string Specimen
        {
            get { return _Specimen; }
            set
            {
                this.OnPropertyValueChange(_.Specimen, _Specimen, value);
                this._Specimen = value;
            }
        }
        /// <summary>
        /// 试管
        /// </summary>
        public string Burette
        {
            get { return _Burette; }
            set
            {
                this.OnPropertyValueChange(_.Burette, _Burette, value);
                this._Burette = value;
            }
        }
        /// <summary>
        /// 身体部位
        /// </summary>
        public string Parts
        {
            get { return _Parts; }
            set
            {
                this.OnPropertyValueChange(_.Parts, _Parts, value);
                this._Parts = value;
            }
        }
        /// <summary>
        /// 下嘱科室
        /// </summary>
        public string DeptCode
        {
            get { return _DeptCode; }
            set
            {
                this.OnPropertyValueChange(_.DeptCode, _DeptCode, value);
                this._DeptCode = value;
            }
        }
        /// <summary>
        /// 下嘱医生ID
        /// </summary>
        public string UserID
        {
            get { return _UserID; }
            set
            {
                this.OnPropertyValueChange(_.UserID, _UserID, value);
                this._UserID = value;
            }
        }
        /// <summary>
        /// 下嘱时间
        /// </summary>
        public DateTime? UpdateTime
        {
            get { return _UpdateTime; }
            set
            {
                this.OnPropertyValueChange(_.UpdateTime, _UpdateTime, value);
                this._UpdateTime = value;
            }
        }
        /// <summary>
        /// 状态  OP_Dic_Process 对应
        /// </summary>
        public int? Status
        {
            get { return _Status; }
            set
            {
                this.OnPropertyValueChange(_.Status, _Status, value);
                this._Status = value;
            }
        }
        /// <summary>
        /// 是否加急 0 否 1是
        /// </summary>
        public int? IsExpedited
        {
            get { return _IsExpedited; }
            set
            {
                this.OnPropertyValueChange(_.IsExpedited, _IsExpedited, value);
                this._IsExpedited = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? HerbalMedicineNum
        {
            get { return _HerbalMedicineNum; }
            set
            {
                this.OnPropertyValueChange(_.HerbalMedicineNum, _HerbalMedicineNum, value);
                this._HerbalMedicineNum = value;
            }
        }
        /// <summary>
        /// 诊断名称
        /// </summary>
        public string DiagnosisName
        {
            get { return _DiagnosisName; }
            set
            {
                this.OnPropertyValueChange(_.DiagnosisName, _DiagnosisName, value);
                this._DiagnosisName = value;
            }
        }
        /// <summary>
        /// 身份证号
        /// </summary>
        public string IDCard
        {
            get { return _IDCard; }
            set
            {
                this.OnPropertyValueChange(_.IDCard, _IDCard, value);
                this._IDCard = value;
            }
        }
        /// <summary>
        /// 医生短号
        /// </summary>
        public string DoctorPhone
        {
            get { return _DoctorPhone; }
            set
            {
                this.OnPropertyValueChange(_.DoctorPhone, _DoctorPhone, value);
                this._DoctorPhone = value;
            }
        }
        /// <summary>
        /// 医生短号
        /// </summary>
        public string PayType
        {
            get { return _PayType; }
            set
            {
                this.OnPropertyValueChange(_.PayType, _PayType, value);
                this._PayType = value;
            }
        }
        /// <summary>
        /// 医生姓名
        /// </summary>
        public string UserName
        {
            get { return _UserName; }
            set
            {
                this.OnPropertyValueChange(_.UserName, _UserName, value);
                this._UserName = value;
            }
        }  /// <summary>
           /// 病人姓名
           /// </summary>
        public string Sex
        {
            get { return _Sex; }
            set
            {
                this.OnPropertyValueChange(_.Sex, _Sex, value);
                this._Sex = value;
            }
        }
        /// <summary>
        /// 病人性别
        /// </summary>
        public string Age
        {
            get { return _Age; }
            set
            {
                this.OnPropertyValueChange(_.Age, _Age, value);
                this._Age = value;
            }
        }
        /// <summary>
        /// his接口,处方单号
        /// </summary>
        public int HISInterface_PrescriptionNo
        {
            get { return _HISInterface_PrescriptionNo; }
            set
            {
                this.OnPropertyValueChange(_.HISInterface_PrescriptionNo, _HISInterface_PrescriptionNo, value);
                this._HISInterface_PrescriptionNo = value;
            }
        }
        /// <summary>
        /// 社保卡号
        /// </summary>
        public string CardNo
        {
            get { return _CardNo; }
            set
            {
                this.OnPropertyValueChange(_.CardNo, _CardNo, value);
                this._CardNo = value;
            }
        }
        /// <summary>
        /// 膏方名称
        /// </summary>
        public string HerbsGroupName
        {
            get { return _HerbsGroupName; }
            set
            {
                this.OnPropertyValueChange(_.HerbsGroupName, _HerbsGroupName, value);
                this._HerbsGroupName = value;
            }
        }
        /// <summary>
        /// 处方流转处方编号
        /// </summary>
        public string PrescriptionCirculation_PrescriptionNo
        {
            get { return _PrescriptionCirculation_PrescriptionNo; }
            set
            {
                this.OnPropertyValueChange(_.PrescriptionCirculation_PrescriptionNo, _PrescriptionCirculation_PrescriptionNo, value);
                this._PrescriptionCirculation_PrescriptionNo = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.TreatmentNo,
                _.PatientID,
                _.PrescriptionNo,
                _.RecordNumber,
                _.PrescriptionType,
                _.Explanation,
                _.ConditionSummary,
                _.Specimen,
                _.Burette,
                _.Parts,
                _.DeptCode,
                _.UserID,
                _.UpdateTime,
                _.Status,
                _.IsExpedited,
                _.HerbalMedicineNum,
            _.DiagnosisName,
            _.IDCard,
            _.DoctorPhone,
            _.PayType,
            _.UserName,
            _.Sex,
            _.Age,
            _.HISInterface_PrescriptionNo,
            _.CardNo,
            _.HerbsGroupName,
            _.PrescriptionCirculation_PrescriptionNo
        };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._TreatmentNo,
                this._PatientID,
                this._PrescriptionNo,
                this._RecordNumber,
                this._PrescriptionType,
                this._Explanation,
                this._ConditionSummary,
                this._Specimen,
                this._Burette,
                this._Parts,
                this._DeptCode,
                this._UserID,
                this._UpdateTime,
                this._Status,
                this._IsExpedited,
                this._HerbalMedicineNum,
            this._DiagnosisName,
            this._IDCard,
            this._DoctorPhone,
            this._PayType,
            this._UserName,
            this._Age,
            this._Sex,
            this._HISInterface_PrescriptionNo,
            this._CardNo,
            this._HerbsGroupName,
            this._PrescriptionCirculation_PrescriptionNo
            };
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "OP_Prescription");
            /// <summary>
            /// ID
            /// </summary>
            public readonly static Field ID = new Field("ID", "OP_Prescription", "ID");
            /// <summary>
            /// 就诊号
            /// </summary>
            public readonly static Field TreatmentNo = new Field("TreatmentNo", "OP_Prescription", "就诊号");
            /// <summary>
            /// 患者ID
            /// </summary>
            public readonly static Field PatientID = new Field("PatientID", "OP_Prescription", "患者ID");
            /// <summary>
            /// 患者姓名
            /// </summary>
            public readonly static Field PatientName = new Field("PatientName", "OP_Prescription", "患者姓名");
            /// <summary>
            /// 处方编号
            /// </summary>
            public readonly static Field PrescriptionNo = new Field("PrescriptionNo", "OP_Prescription", "处方编号");
            /// <summary>
            /// 记录数量
            /// </summary>
            public readonly static Field RecordNumber = new Field("RecordNumber", "OP_Prescription", "记录数量");
            /// <summary>
            /// 处方类别
            /// </summary>
            public readonly static Field PrescriptionType = new Field("PrescriptionType", "OP_Prescription", "处方类别");
            /// <summary>
            /// 医生说明
            /// </summary>
            public readonly static Field Explanation = new Field("Explanation", "OP_Prescription", "医生说明");
            /// <summary>
            /// 病史摘要
            /// </summary>
            public readonly static Field ConditionSummary = new Field("ConditionSummary", "OP_Prescription", "病史摘要");
            /// <summary>
            /// 标本
            /// </summary>
            public readonly static Field Specimen = new Field("Specimen", "OP_Prescription", "标本");
            /// <summary>
            /// 试管
            /// </summary>
            public readonly static Field Burette = new Field("Burette", "OP_Prescription", "试管");
            /// <summary>
            /// 身体部位
            /// </summary>
            public readonly static Field Parts = new Field("Parts", "OP_Prescription", "身体部位");
            /// <summary>
            /// 下嘱科室
            /// </summary>
            public readonly static Field DeptCode = new Field("DeptCode", "OP_Prescription", "下嘱科室");
            /// <summary>
            /// 下嘱医生ID
            /// </summary>
            public readonly static Field UserID = new Field("UserID", "OP_Prescription", "下嘱医生ID");
            /// <summary>
            /// 下嘱时间
            /// </summary>
            public readonly static Field UpdateTime = new Field("UpdateTime", "OP_Prescription", "下嘱时间");
            /// <summary>
            /// 状态  OP_Dic_Process 对应
            /// </summary>
            public readonly static Field Status = new Field("Status", "OP_Prescription", "状态  OP_Dic_Process 对应");
            /// <summary>
            /// 是否加急 0 否 1是
            /// </summary>
            public readonly static Field IsExpedited = new Field("IsExpedited", "OP_Prescription", "是否加急 0 否 1是");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field HerbalMedicineNum = new Field("HerbalMedicineNum", "OP_Prescription", "HerbalMedicineNum");
            /// <summary>
            /// 诊断信息
            /// </summary>
            public readonly static Field DiagnosisName = new Field("DiagnosisName", "OP_Prescription", "DiagnosisName");
            /// <summary>
            /// 身份证号
            /// </summary>
            public readonly static Field IDCard = new Field("IDCard", "OP_Prescription", "IDCard");
            /// <summary>
            /// 医生短号
            /// </summary>
            public readonly static Field DoctorPhone = new Field("DoctorPhone", "OP_Prescription", "医生短号");
            /// <summary>
            /// 医生短号
            /// </summary>
            public readonly static Field PayType = new Field("PayType", "OP_Prescription", "医生短号");
            /// <summary>
            /// 医生短号
            /// </summary>
            public readonly static Field UserName = new Field("UserName", "OP_Prescription", "医生短号");
            /// <summary>
            /// 医生短号
            /// </summary>
            public readonly static Field Sex = new Field("Sex", "OP_Prescription", "医生短号");
            /// <summary>
            /// 医生短号
            /// </summary>
            public readonly static Field Age = new Field("Age", "OP_Prescription", "医生短号");
            /// <summary>
            /// his接口,处方单号
            /// </summary>
            public readonly static Field HISInterface_PrescriptionNo = new Field("HISInterface_PrescriptionNo", "OP_Prescription", "his接口,处方单号");
            /// <summary>
            /// 社保卡号
            /// </summary>
            public readonly static Field CardNo = new Field("CardNo", "OP_Prescription", "社保卡号");
            /// <summary>
            /// 膏方名称
            /// </summary>
            public readonly static Field HerbsGroupName = new Field("HerbsGroupName", "OP_Prescription", "膏方名称");
            /// <summary>
            /// 处方流转处方编号
            /// </summary>
            public readonly static Field PrescriptionCirculation_PrescriptionNo = new Field("PrescriptionCirculation_PrescriptionNo", "OP_Prescription", "处方流转处方编号");
        }
        #endregion


    }
}

