//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
	/// <summary>
	/// 实体类OP_ReportValue。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("OP_ReportValue")]
	[Serializable]
	public partial class OP_ReportValue : Entity
	{
		#region Model
		private long _Id;
		private string _PatientName;
		private string _TreamentNo;
		private string _DoctorCode;
		private string _DeptCode;
		private string _ReportName;
		private string _FieldName;
		private string _FileldID;
		private string _FileldValue;
		private string _ReportID;
		private int? _Staus;
		private DateTime? _CreateDateTime;
		private string _CreateUserCode;
		private DateTime? _LastModifyDatetime;
		private string _LastModifyUserCode;
		private DateTime? _DeleteDatetime;
		private string _DeleteUserCode;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PatientName")]
		public string PatientName
		{
			get { return _PatientName; }
			set
			{
				this.OnPropertyValueChange("PatientName");
				this._PatientName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TreamentNo")]
		public string TreamentNo
		{
			get { return _TreamentNo; }
			set
			{
				this.OnPropertyValueChange("TreamentNo");
				this._TreamentNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DoctorCode")]
		public string DoctorCode
		{
			get { return _DoctorCode; }
			set
			{
				this.OnPropertyValueChange("DoctorCode");
				this._DoctorCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptCode")]
		public string DeptCode
		{
			get { return _DeptCode; }
			set
			{
				this.OnPropertyValueChange("DeptCode");
				this._DeptCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReportName")]
		public string ReportName
		{
			get { return _ReportName; }
			set
			{
				this.OnPropertyValueChange("ReportName");
				this._ReportName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FieldName")]
		public string FieldName
		{
			get { return _FieldName; }
			set
			{
				this.OnPropertyValueChange("FieldName");
				this._FieldName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FileldID")]
		public string FileldID
		{
			get { return _FileldID; }
			set
			{
				this.OnPropertyValueChange("FileldID");
				this._FileldID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FileldValue")]
		public string FileldValue
		{
			get { return _FileldValue; }
			set
			{
				this.OnPropertyValueChange("FileldValue");
				this._FileldValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReportID")]
		public string ReportID
		{
			get { return _ReportID; }
			set
			{
				this.OnPropertyValueChange("ReportID");
				this._ReportID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Staus")]
		public int? Staus
		{
			get { return _Staus; }
			set
			{
				this.OnPropertyValueChange("Staus");
				this._Staus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateDateTime")]
		public DateTime? CreateDateTime
		{
			get { return _CreateDateTime; }
			set
			{
				this.OnPropertyValueChange("CreateDateTime");
				this._CreateDateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateUserCode")]
		public string CreateUserCode
		{
			get { return _CreateUserCode; }
			set
			{
				this.OnPropertyValueChange("CreateUserCode");
				this._CreateUserCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastModifyDatetime")]
		public DateTime? LastModifyDatetime
		{
			get { return _LastModifyDatetime; }
			set
			{
				this.OnPropertyValueChange("LastModifyDatetime");
				this._LastModifyDatetime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastModifyUserCode")]
		public string LastModifyUserCode
		{
			get { return _LastModifyUserCode; }
			set
			{
				this.OnPropertyValueChange("LastModifyUserCode");
				this._LastModifyUserCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeleteDatetime")]
		public DateTime? DeleteDatetime
		{
			get { return _DeleteDatetime; }
			set
			{
				this.OnPropertyValueChange("DeleteDatetime");
				this._DeleteDatetime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeleteUserCode")]
		public string DeleteUserCode
		{
			get { return _DeleteUserCode; }
			set
			{
				this.OnPropertyValueChange("DeleteUserCode");
				this._DeleteUserCode = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.PatientName,
				_.TreamentNo,
				_.DoctorCode,
				_.DeptCode,
				_.ReportName,
				_.FieldName,
				_.FileldID,
				_.FileldValue,
				_.ReportID,
				_.Staus,
				_.CreateDateTime,
				_.CreateUserCode,
				_.LastModifyDatetime,
				_.LastModifyUserCode,
				_.DeleteDatetime,
				_.DeleteUserCode,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._PatientName,
				this._TreamentNo,
				this._DoctorCode,
				this._DeptCode,
				this._ReportName,
				this._FieldName,
				this._FileldID,
				this._FileldValue,
				this._ReportID,
				this._Staus,
				this._CreateDateTime,
				this._CreateUserCode,
				this._LastModifyDatetime,
				this._LastModifyUserCode,
				this._DeleteDatetime,
				this._DeleteUserCode,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "OP_ReportValue");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientName = new Field("PatientName", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TreamentNo = new Field("TreamentNo", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorCode = new Field("DoctorCode", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReportName = new Field("ReportName", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FieldName = new Field("FieldName", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FileldID = new Field("FileldID", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FileldValue = new Field("FileldValue", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReportID = new Field("ReportID", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Staus = new Field("Staus", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateDateTime = new Field("CreateDateTime", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserCode = new Field("CreateUserCode", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastModifyDatetime = new Field("LastModifyDatetime", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastModifyUserCode = new Field("LastModifyUserCode", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeleteDatetime = new Field("DeleteDatetime", "OP_ReportValue", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeleteUserCode = new Field("DeleteUserCode", "OP_ReportValue", "");
		}
		#endregion
	}
}