//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类OP_ReportSummary。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Serializable]
    public partial class OP_ReportSummary : Entity,ICloneable
    {
		public OP_ReportSummary() : base("OP_ReportSummary") { }

        #region Model
		private string _ID;
		private object _XML;
		private string _TreatmentNo;
		private string _DeptCode;
		private string _DoctorCode;
		private DateTime? _UpdateTime;
		private string _TypeName;

		/// <summary>
		/// 
		/// </summary>
		public string ID
		{
			get{ return _ID; }
			set
			{
				if(this._ID == value)
				this.OnPropertyValueChange(_.ID, _ID, value);
				this._ID = value;
			}
		}
		/// <summary>
		/// 文档xml
		/// </summary>
		public object XML
		{
			get{ return _XML; }
			set
			{
				if(this._XML == value)
				this.OnPropertyValueChange(_.XML, _XML, value);
				this._XML = value;
			}
		}
		/// <summary>
		/// 就诊号
		/// </summary>
		public string TreatmentNo
		{
			get{ return _TreatmentNo; }
			set
			{
				if(this._TreatmentNo == value)
				this.OnPropertyValueChange(_.TreatmentNo, _TreatmentNo, value);
				this._TreatmentNo = value;
			}
		}
		/// <summary>
		/// 科室编号
		/// </summary>
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				if(this._DeptCode == value)
				this.OnPropertyValueChange(_.DeptCode, _DeptCode, value);
				this._DeptCode = value;
			}
		}
		/// <summary>
		/// 医生编号
		/// </summary>
		public string DoctorCode
		{
			get{ return _DoctorCode; }
			set
			{
				if(this._DoctorCode == value)
				this.OnPropertyValueChange(_.DoctorCode, _DoctorCode, value);
				this._DoctorCode = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				if(this._UpdateTime == value)
				this.OnPropertyValueChange(_.UpdateTime, _UpdateTime, value);
				this._UpdateTime = value;
			}
		}
		/// <summary>
		/// 类型名称
		/// </summary>
		public string TypeName
		{
			get{ return _TypeName; }
			set
			{
				if(this._TypeName == value)
				this.OnPropertyValueChange(_.TypeName, _TypeName, value);
				this._TypeName = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.XML,
				_.TreatmentNo,
				_.DeptCode,
				_.DoctorCode,
				_.UpdateTime,
				_.TypeName,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._XML,
				this._TreatmentNo,
				this._DeptCode,
				this._DoctorCode,
				this._UpdateTime,
				this._TypeName,
			};
        }

		public object Clone()
		{
		 return new OP_ReportSummary {
				ID=this._ID,
				XML=this._XML,
				TreatmentNo=this._TreatmentNo,
				DeptCode=this._DeptCode,
				DoctorCode=this._DoctorCode,
				UpdateTime=this._UpdateTime,
				TypeName=this._TypeName,
			};
		}
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "OP_ReportSummary");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "OP_ReportSummary", "");
            /// <summary>
			/// 文档xml
			/// </summary>
			public readonly static Field XML = new Field("XML", "OP_ReportSummary", "文档xml");
            /// <summary>
			/// 就诊号
			/// </summary>
			public readonly static Field TreatmentNo = new Field("TreatmentNo", "OP_ReportSummary", "就诊号");
            /// <summary>
			/// 科室编号
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "OP_ReportSummary", "科室编号");
            /// <summary>
			/// 医生编号
			/// </summary>
			public readonly static Field DoctorCode = new Field("DoctorCode", "OP_ReportSummary", "医生编号");
            /// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "OP_ReportSummary", "更新时间");
            /// <summary>
			/// 类型名称
			/// </summary>
			public readonly static Field TypeName = new Field("TypeName", "OP_ReportSummary", "类型名称");
        }
        #endregion
	}
}