//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类OP_SpecialMaterialReport。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_SpecialMaterialReport")]
    [Serializable]
    public partial class OP_SpecialMaterialReport : Entity
    {
        #region Model
        private string _ID;
        private string _Content;
        private DateTime? _UpdateTime;
        private string _DoctorCode;
        private string _DeptCode;
        private string _TreatmentNo;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Content")]
        public string Content
        {
            get { return _Content; }
            set
            {
                this.OnPropertyValueChange("Content");
                this._Content = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UpdateTime")]
        public DateTime? UpdateTime
        {
            get { return _UpdateTime; }
            set
            {
                this.OnPropertyValueChange("UpdateTime");
                this._UpdateTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DoctorCode")]
        public string DoctorCode
        {
            get { return _DoctorCode; }
            set
            {
                this.OnPropertyValueChange("DoctorCode");
                this._DoctorCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeptCode")]
        public string DeptCode
        {
            get { return _DeptCode; }
            set
            {
                this.OnPropertyValueChange("DeptCode");
                this._DeptCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TreatmentNo")]
        public string TreatmentNo
        {
            get { return _TreatmentNo; }
            set
            {
                this.OnPropertyValueChange("TreatmentNo");
                this._TreatmentNo = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.Content,
                _.UpdateTime,
                _.DoctorCode,
                _.DeptCode,
                _.TreatmentNo,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._Content,
                this._UpdateTime,
                this._DoctorCode,
                this._DeptCode,
                this._TreatmentNo,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "OP_SpecialMaterialReport");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "OP_SpecialMaterialReport", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content", "OP_SpecialMaterialReport", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "OP_SpecialMaterialReport", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorCode = new Field("DoctorCode", "OP_SpecialMaterialReport", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "OP_SpecialMaterialReport", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TreatmentNo = new Field("TreatmentNo", "OP_SpecialMaterialReport", "");
        }
        #endregion
    }
}