//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_App_Dept 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_App_Dept")]
	[Serializable]
	public partial class Sys_App_Dept : Entity 
	{
		#region Model
		private int? _ID;
		private string _AppCode;
		private string _DeptCode;
		/// <summary>
		/// 
		/// </summary>
		public int? ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 系统代码
		/// </summary>
		public string AppCode
		{
			get{ return _AppCode; }
			set
			{
				this.OnPropertyValueChange(_.AppCode,_AppCode,value);
				this._AppCode=value;
			}
		}
		/// <summary>
		/// 科室代码
		/// </summary>
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange(_.DeptCode,_DeptCode,value);
				this._DeptCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.AppCode,
				_.DeptCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._AppCode,
				this._DeptCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_App_Dept");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","Sys_App_Dept","ID");
			/// <summary>
			/// 系统代码
			/// </summary>
			public readonly static Field AppCode = new Field("AppCode","Sys_App_Dept","系统代码");
			/// <summary>
			/// 科室代码
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode","Sys_App_Dept","科室代码");
		}
		#endregion


	}
}

