//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_User 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_User")]
	[Serializable]
	public partial class Sys_User : Entity 
	{
		#region Model
		private string _ID;
		private string _Code;
		private string _Sex;
		private string _Name;
		private string _Dept_Code;
		private int _Status;
		private string _Type;
		private string _Pwd;
		private string _JobTitle;
		private string _SearchCode;
		/// <summary>
		/// ID
		/// </summary>
		public string ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 代码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange(_.Sex,_Sex,value);
				this._Sex=value;
			}
		}
		/// <summary>
		/// 姓名
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 部门编码
		/// </summary>
		public string Dept_Code
		{
			get{ return _Dept_Code; }
			set
			{
				this.OnPropertyValueChange(_.Dept_Code,_Dept_Code,value);
				this._Dept_Code=value;
			}
		}
		/// <summary>
		/// 用户状态（0停用 1启用）
		/// </summary>
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 人员类型 1医生 2护士 3财务 99其他
		/// </summary>
		public string Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 密码
		/// </summary>
		public string Pwd
		{
			get{ return _Pwd; }
			set
			{
				this.OnPropertyValueChange(_.Pwd,_Pwd,value);
				this._Pwd=value;
			}
		}
		/// <summary>
		/// 职称
		/// </summary>
		public string JobTitle
		{
			get{ return _JobTitle; }
			set
			{
				this.OnPropertyValueChange(_.JobTitle,_JobTitle,value);
				this._JobTitle=value;
			}
		}
		/// <summary>
		/// 检索码
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Code,
				_.Sex,
				_.Name,
				_.Dept_Code,
				_.Status,
				_.Type,
				_.Pwd,
				_.JobTitle,
				_.SearchCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Code,
				this._Sex,
				this._Name,
				this._Dept_Code,
				this._Status,
				this._Type,
				this._Pwd,
				this._JobTitle,
				this._SearchCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_User");
			/// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID","Sys_User","ID");
			/// <summary>
			/// 代码
			/// </summary>
			public readonly static Field Code = new Field("Code","Sys_User","代码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex","Sys_User","Sex");
			/// <summary>
			/// 姓名
			/// </summary>
			public readonly static Field Name = new Field("Name","Sys_User","姓名");
			/// <summary>
			/// 部门编码
			/// </summary>
			public readonly static Field Dept_Code = new Field("Dept_Code","Sys_User","部门编码");
			/// <summary>
			/// 用户状态（0停用 1启用）
			/// </summary>
			public readonly static Field Status = new Field("Status","Sys_User","用户状态（0停用 1启用）");
			/// <summary>
			/// 人员类型 1医生 2护士 3财务 99其他
			/// </summary>
			public readonly static Field Type = new Field("Type","Sys_User","人员类型 1医生 2护士 3财务 99其他");
			/// <summary>
			/// 密码
			/// </summary>
			public readonly static Field Pwd = new Field("Pwd","Sys_User","密码");
			/// <summary>
			/// 职称
			/// </summary>
			public readonly static Field JobTitle = new Field("JobTitle","Sys_User","职称");
			/// <summary>
			/// 检索码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","Sys_User","检索码");
		}
		#endregion


	}
}

