//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_LoginLog 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_LoginLog")]
	[Serializable]
	public partial class Sys_LoginLog : Entity 
	{
		#region Model
		private string _ID;
		private string _UserID;
		private DateTime? _InTime;
		private DateTime? _OutTime;
		private string _IPAddress;
		private string _SystemID;
		/// <summary>
		/// 编号
		/// </summary>
		public string ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 登录用户
		/// </summary>
		public string UserID
		{
			get{ return _UserID; }
			set
			{
				this.OnPropertyValueChange(_.UserID,_UserID,value);
				this._UserID=value;
			}
		}
		/// <summary>
		/// 系统登录时间
		/// </summary>
		public DateTime? InTime
		{
			get{ return _InTime; }
			set
			{
				this.OnPropertyValueChange(_.InTime,_InTime,value);
				this._InTime=value;
			}
		}
		/// <summary>
		/// 系统登出时间
		/// </summary>
		public DateTime? OutTime
		{
			get{ return _OutTime; }
			set
			{
				this.OnPropertyValueChange(_.OutTime,_OutTime,value);
				this._OutTime=value;
			}
		}
		/// <summary>
		/// IP地址
		/// </summary>
		public string IPAddress
		{
			get{ return _IPAddress; }
			set
			{
				this.OnPropertyValueChange(_.IPAddress,_IPAddress,value);
				this._IPAddress=value;
			}
		}
		/// <summary>
		/// 系统
		/// </summary>
		public string SystemID
		{
			get{ return _SystemID; }
			set
			{
				this.OnPropertyValueChange(_.SystemID,_SystemID,value);
				this._SystemID=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.UserID,
				_.InTime,
				_.OutTime,
				_.IPAddress,
				_.SystemID};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._UserID,
				this._InTime,
				this._OutTime,
				this._IPAddress,
				this._SystemID};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_LoginLog");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field ID = new Field("ID","Sys_LoginLog","编号");
			/// <summary>
			/// 登录用户
			/// </summary>
			public readonly static Field UserID = new Field("UserID","Sys_LoginLog","登录用户");
			/// <summary>
			/// 系统登录时间
			/// </summary>
			public readonly static Field InTime = new Field("InTime","Sys_LoginLog","系统登录时间");
			/// <summary>
			/// 系统登出时间
			/// </summary>
			public readonly static Field OutTime = new Field("OutTime","Sys_LoginLog","系统登出时间");
			/// <summary>
			/// IP地址
			/// </summary>
			public readonly static Field IPAddress = new Field("IPAddress","Sys_LoginLog","IP地址");
			/// <summary>
			/// 系统
			/// </summary>
			public readonly static Field SystemID = new Field("SystemID","Sys_LoginLog","系统");
		}
		#endregion


	}
}

