//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_Parameter 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_Parameter")]
	[Serializable]
	public partial class Sys_Parameter : Entity 
	{
		#region Model
		private int _ID;
		private string _ParameterCode;
		private string _ParameterName;
		private string _ParameterValue;
		private string _Description;
		private int? _Status;
		private string _Creator;
		private DateTime? _CreateDate;
		private string _LastEditor;
		private DateTime? _EditDate;
		private string _RNO;
		private string _SearchCode;
		/// <summary>
		/// ID
		/// </summary>
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 参数代码
		/// </summary>
		public string ParameterCode
		{
			get{ return _ParameterCode; }
			set
			{
				this.OnPropertyValueChange(_.ParameterCode,_ParameterCode,value);
				this._ParameterCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ParameterName
		{
			get{ return _ParameterName; }
			set
			{
				this.OnPropertyValueChange(_.ParameterName,_ParameterName,value);
				this._ParameterName=value;
			}
		}
		/// <summary>
		/// 参数值
		/// </summary>
		public string ParameterValue
		{
			get{ return _ParameterValue; }
			set
			{
				this.OnPropertyValueChange(_.ParameterValue,_ParameterValue,value);
				this._ParameterValue=value;
			}
		}
		/// <summary>
		/// 描述
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 参数状态（0可编辑 1不可编辑 2停用）
		/// </summary>
		public int? Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 创建者
		/// </summary>
		public string Creator
		{
			get{ return _Creator; }
			set
			{
				this.OnPropertyValueChange(_.Creator,_Creator,value);
				this._Creator=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate=value;
			}
		}
		/// <summary>
		/// 最后一次修改者
		/// </summary>
		public string LastEditor
		{
			get{ return _LastEditor; }
			set
			{
				this.OnPropertyValueChange(_.LastEditor,_LastEditor,value);
				this._LastEditor=value;
			}
		}
		/// <summary>
		/// 最后修改时间
		/// </summary>
		public DateTime? EditDate
		{
			get{ return _EditDate; }
			set
			{
				this.OnPropertyValueChange(_.EditDate,_EditDate,value);
				this._EditDate=value;
			}
		}
		/// <summary>
		/// 所属系统（默认为Global  代表全局参数）
		/// </summary>
		public string RNO
		{
			get{ return _RNO; }
			set
			{
				this.OnPropertyValueChange(_.RNO,_RNO,value);
				this._RNO=value;
			}
		}
		/// <summary>
		/// 检索码
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.ParameterCode,
				_.ParameterName,
				_.ParameterValue,
				_.Description,
				_.Status,
				_.Creator,
				_.CreateDate,
				_.LastEditor,
				_.EditDate,
				_.RNO,
				_.SearchCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._ParameterCode,
				this._ParameterName,
				this._ParameterValue,
				this._Description,
				this._Status,
				this._Creator,
				this._CreateDate,
				this._LastEditor,
				this._EditDate,
				this._RNO,
				this._SearchCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_Parameter");
			/// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID","Sys_Parameter","ID");
			/// <summary>
			/// 参数代码
			/// </summary>
			public readonly static Field ParameterCode = new Field("ParameterCode","Sys_Parameter","参数代码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParameterName = new Field("ParameterName","Sys_Parameter","ParameterName");
			/// <summary>
			/// 参数值
			/// </summary>
			public readonly static Field ParameterValue = new Field("ParameterValue","Sys_Parameter","参数值");
			/// <summary>
			/// 描述
			/// </summary>
			public readonly static Field Description = new Field("Description","Sys_Parameter","描述");
			/// <summary>
			/// 参数状态（0可编辑 1不可编辑 2停用）
			/// </summary>
			public readonly static Field Status = new Field("Status","Sys_Parameter","参数状态（0可编辑 1不可编辑 2停用）");
			/// <summary>
			/// 创建者
			/// </summary>
			public readonly static Field Creator = new Field("Creator","Sys_Parameter","创建者");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","Sys_Parameter","创建时间");
			/// <summary>
			/// 最后一次修改者
			/// </summary>
			public readonly static Field LastEditor = new Field("LastEditor","Sys_Parameter","最后一次修改者");
			/// <summary>
			/// 最后修改时间
			/// </summary>
			public readonly static Field EditDate = new Field("EditDate","Sys_Parameter","最后修改时间");
			/// <summary>
			/// 所属系统（默认为Global  代表全局参数）
			/// </summary>
			public readonly static Field RNO = new Field("RNO","Sys_Parameter","所属系统（默认为Global  代表全局参数）");
			/// <summary>
			/// 检索码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","Sys_Parameter","检索码");
		}
		#endregion


	}
}

