//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_Message 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_Message")]
	[Serializable]
	public partial class Sys_Message : Entity 
	{
		#region Model
		private int _ID;
		private string _Title;
		private string _RTFContext;
		private string _TextContext;
		private int? _Type;
		private DateTime? _Time;
		private string _ReleasePerple;
		private int? _Status;
		/// <summary>
		/// 
		/// </summary>
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RTFContext
		{
			get{ return _RTFContext; }
			set
			{
				this.OnPropertyValueChange(_.RTFContext,_RTFContext,value);
				this._RTFContext=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TextContext
		{
			get{ return _TextContext; }
			set
			{
				this.OnPropertyValueChange(_.TextContext,_TextContext,value);
				this._TextContext=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Time
		{
			get{ return _Time; }
			set
			{
				this.OnPropertyValueChange(_.Time,_Time,value);
				this._Time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ReleasePerple
		{
			get{ return _ReleasePerple; }
			set
			{
				this.OnPropertyValueChange(_.ReleasePerple,_ReleasePerple,value);
				this._ReleasePerple=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ID;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Title,
				_.RTFContext,
				_.TextContext,
				_.Type,
				_.Time,
				_.ReleasePerple,
				_.Status};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Title,
				this._RTFContext,
				this._TextContext,
				this._Type,
				this._Time,
				this._ReleasePerple,
				this._Status};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_Message");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","Sys_Message","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","Sys_Message","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RTFContext = new Field("RTFContext","Sys_Message","RTFContext");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TextContext = new Field("TextContext","Sys_Message","TextContext");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type","Sys_Message","Type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Time = new Field("Time","Sys_Message","Time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReleasePerple = new Field("ReleasePerple","Sys_Message","ReleasePerple");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Status = new Field("Status","Sys_Message","Status");
		}
		#endregion


	}
}

