//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_Dept_Subsidiary 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_Dept_Subsidiary")]
	[Serializable]
	public partial class Sys_Dept_Subsidiary : Entity 
	{
		#region Model
		private string _ID;
		private string _Code;
		private string _Name;
		private string _Introduction;
		private string _Feature;
		private string _Position;
		/// <summary>
		/// ID
		/// </summary>
		public string ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 代码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 科室介绍
		/// </summary>
		public string Introduction
		{
			get{ return _Introduction; }
			set
			{
				this.OnPropertyValueChange(_.Introduction,_Introduction,value);
				this._Introduction=value;
			}
		}
		/// <summary>
		/// 科室特色
		/// </summary>
		public string Feature
		{
			get{ return _Feature; }
			set
			{
				this.OnPropertyValueChange(_.Feature,_Feature,value);
				this._Feature=value;
			}
		}
		/// <summary>
		/// 科室位置
		/// </summary>
		public string Position
		{
			get{ return _Position; }
			set
			{
				this.OnPropertyValueChange(_.Position,_Position,value);
				this._Position=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Code,
				_.Name,
				_.Introduction,
				_.Feature,
				_.Position};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Code,
				this._Name,
				this._Introduction,
				this._Feature,
				this._Position};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_Dept_Subsidiary");
			/// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID","Sys_Dept_Subsidiary","ID");
			/// <summary>
			/// 代码
			/// </summary>
			public readonly static Field Code = new Field("Code","Sys_Dept_Subsidiary","代码");
			/// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name","Sys_Dept_Subsidiary","名称");
			/// <summary>
			/// 科室介绍
			/// </summary>
			public readonly static Field Introduction = new Field("Introduction","Sys_Dept_Subsidiary","科室介绍");
			/// <summary>
			/// 科室特色
			/// </summary>
			public readonly static Field Feature = new Field("Feature","Sys_Dept_Subsidiary","科室特色");
			/// <summary>
			/// 科室位置
			/// </summary>
			public readonly static Field Position = new Field("Position","Sys_Dept_Subsidiary","科室位置");
		}
		#endregion


	}
}

