//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_User_Subsidiary 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_User_Subsidiary")]
	[Serializable]
	public partial class Sys_User_Subsidiary : Entity 
	{
		#region Model
		private string _ID;
		private string _Code;
		private string _Name;
		private string _Sex;
		private DateTime? _Birthday;
		private string _Dept_Code;
		private string _IDCard;
		private string _Introduction;
		private string _Feature;
		private string _EducationaBackground;
		/// <summary>
		/// ID
		/// </summary>
		public string ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 编码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 姓名
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 性别
		/// </summary>
		public string Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange(_.Sex,_Sex,value);
				this._Sex=value;
			}
		}
		/// <summary>
		/// 生日
		/// </summary>
		public DateTime? Birthday
		{
			get{ return _Birthday; }
			set
			{
				this.OnPropertyValueChange(_.Birthday,_Birthday,value);
				this._Birthday=value;
			}
		}
		/// <summary>
		/// 部门名称
		/// </summary>
		public string Dept_Code
		{
			get{ return _Dept_Code; }
			set
			{
				this.OnPropertyValueChange(_.Dept_Code,_Dept_Code,value);
				this._Dept_Code=value;
			}
		}
		/// <summary>
		/// 身份证号
		/// </summary>
		public string IDCard
		{
			get{ return _IDCard; }
			set
			{
				this.OnPropertyValueChange(_.IDCard,_IDCard,value);
				this._IDCard=value;
			}
		}
		/// <summary>
		/// 人员介绍
		/// </summary>
		public string Introduction
		{
			get{ return _Introduction; }
			set
			{
				this.OnPropertyValueChange(_.Introduction,_Introduction,value);
				this._Introduction=value;
			}
		}
		/// <summary>
		/// 人员特点
		/// </summary>
		public string Feature
		{
			get{ return _Feature; }
			set
			{
				this.OnPropertyValueChange(_.Feature,_Feature,value);
				this._Feature=value;
			}
		}
		/// <summary>
		/// 学历
		/// </summary>
		public string EducationaBackground
		{
			get{ return _EducationaBackground; }
			set
			{
				this.OnPropertyValueChange(_.EducationaBackground,_EducationaBackground,value);
				this._EducationaBackground=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Code,
				_.Name,
				_.Sex,
				_.Birthday,
				_.Dept_Code,
				_.IDCard,
				_.Introduction,
				_.Feature,
				_.EducationaBackground};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Code,
				this._Name,
				this._Sex,
				this._Birthday,
				this._Dept_Code,
				this._IDCard,
				this._Introduction,
				this._Feature,
				this._EducationaBackground};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_User_Subsidiary");
			/// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID","Sys_User_Subsidiary","ID");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Code = new Field("Code","Sys_User_Subsidiary","编码");
			/// <summary>
			/// 姓名
			/// </summary>
			public readonly static Field Name = new Field("Name","Sys_User_Subsidiary","姓名");
			/// <summary>
			/// 性别
			/// </summary>
			public readonly static Field Sex = new Field("Sex","Sys_User_Subsidiary","性别");
			/// <summary>
			/// 生日
			/// </summary>
			public readonly static Field Birthday = new Field("Birthday","Sys_User_Subsidiary","生日");
			/// <summary>
			/// 部门名称
			/// </summary>
			public readonly static Field Dept_Code = new Field("Dept_Code","Sys_User_Subsidiary","部门名称");
			/// <summary>
			/// 身份证号
			/// </summary>
			public readonly static Field IDCard = new Field("IDCard","Sys_User_Subsidiary","身份证号");
			/// <summary>
			/// 人员介绍
			/// </summary>
			public readonly static Field Introduction = new Field("Introduction","Sys_User_Subsidiary","人员介绍");
			/// <summary>
			/// 人员特点
			/// </summary>
			public readonly static Field Feature = new Field("Feature","Sys_User_Subsidiary","人员特点");
			/// <summary>
			/// 学历
			/// </summary>
			public readonly static Field EducationaBackground = new Field("EducationaBackground","Sys_User_Subsidiary","学历");
		}
		#endregion


	}
}

