//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_Dic_Surgery 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_Dic_Surgery")]
	[Serializable]
	public partial class Sys_Dic_Surgery : Entity 
	{
		#region Model
		private string _Code;
		private string _Name;
		private int? _Level_GB;
		private int? _Level_Inside;
		private int? _IncisionType;
		private int? _DoctorNumber;
		private string _Category;
		private string _DeptCode;
		private int? _Status;
		private string _SearchCode;
		/// <summary>
		/// 手术编码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 手术名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 手术级别(卫计委)
		/// </summary>
		public int? Level_GB
		{
			get{ return _Level_GB; }
			set
			{
				this.OnPropertyValueChange(_.Level_GB,_Level_GB,value);
				this._Level_GB=value;
			}
		}
		/// <summary>
		/// 手术级别(医院内部)
		/// </summary>
		public int? Level_Inside
		{
			get{ return _Level_Inside; }
			set
			{
				this.OnPropertyValueChange(_.Level_Inside,_Level_Inside,value);
				this._Level_Inside=value;
			}
		}
		/// <summary>
		/// 切口分类
		/// </summary>
		public int? IncisionType
		{
			get{ return _IncisionType; }
			set
			{
				this.OnPropertyValueChange(_.IncisionType,_IncisionType,value);
				this._IncisionType=value;
			}
		}
		/// <summary>
		/// 医生人数
		/// </summary>
		public int? DoctorNumber
		{
			get{ return _DoctorNumber; }
			set
			{
				this.OnPropertyValueChange(_.DoctorNumber,_DoctorNumber,value);
				this._DoctorNumber=value;
			}
		}
		/// <summary>
		/// 手术范畴（手术、介入、操作）
		/// </summary>
		public string Category
		{
			get{ return _Category; }
			set
			{
				this.OnPropertyValueChange(_.Category,_Category,value);
				this._Category=value;
			}
		}
		/// <summary>
		/// 开展该手术的科室编号
		/// </summary>
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange(_.DeptCode,_DeptCode,value);
				this._DeptCode=value;
			}
		}
		/// <summary>
		/// 手术状态 0停止开展 1正常开展
		/// </summary>
		public int? Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 搜索码
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Code};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Code,
				_.Name,
				_.Level_GB,
				_.Level_Inside,
				_.IncisionType,
				_.DoctorNumber,
				_.Category,
				_.DeptCode,
				_.Status,
				_.SearchCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Code,
				this._Name,
				this._Level_GB,
				this._Level_Inside,
				this._IncisionType,
				this._DoctorNumber,
				this._Category,
				this._DeptCode,
				this._Status,
				this._SearchCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_Dic_Surgery");
			/// <summary>
			/// 手术编码
			/// </summary>
			public readonly static Field Code = new Field("Code","Sys_Dic_Surgery","手术编码");
			/// <summary>
			/// 手术名称
			/// </summary>
			public readonly static Field Name = new Field("Name","Sys_Dic_Surgery","手术名称");
			/// <summary>
			/// 手术级别(卫计委)
			/// </summary>
			public readonly static Field Level_GB = new Field("Level_GB","Sys_Dic_Surgery","手术级别(卫计委)");
			/// <summary>
			/// 手术级别(医院内部)
			/// </summary>
			public readonly static Field Level_Inside = new Field("Level_Inside","Sys_Dic_Surgery","手术级别(医院内部)");
			/// <summary>
			/// 切口分类
			/// </summary>
			public readonly static Field IncisionType = new Field("IncisionType","Sys_Dic_Surgery","切口分类");
			/// <summary>
			/// 医生人数
			/// </summary>
			public readonly static Field DoctorNumber = new Field("DoctorNumber","Sys_Dic_Surgery","医生人数");
			/// <summary>
			/// 手术范畴（手术、介入、操作）
			/// </summary>
			public readonly static Field Category = new Field("Category","Sys_Dic_Surgery","手术范畴（手术、介入、操作）");
			/// <summary>
			/// 开展该手术的科室编号
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode","Sys_Dic_Surgery","开展该手术的科室编号");
			/// <summary>
			/// 手术状态 0停止开展 1正常开展
			/// </summary>
			public readonly static Field Status = new Field("Status","Sys_Dic_Surgery","手术状态 0停止开展 1正常开展");
			/// <summary>
			/// 搜索码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","Sys_Dic_Surgery","搜索码");
		}
		#endregion


	}
}

