//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类Sys_Dic_ICD 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_Dic_ICD")]
	[Serializable]
	public partial class Sys_Dic_ICD : Entity 
	{
		#region Model
		private string _Code;
		private string _InsideCode;
		private string _Name;
		private string _SearchCode;
		private int? _DiseasesLevel;
		private int? _Days;
		private decimal? _Cost;
		/// <summary>
		/// 疾病代码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 医院内部编码（如果没有则和Code一致）
		/// </summary>
		public string InsideCode
		{
			get{ return _InsideCode; }
			set
			{
				this.OnPropertyValueChange(_.InsideCode,_InsideCode,value);
				this._InsideCode=value;
			}
		}
		/// <summary>
		/// 疾病名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 检索码
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		/// <summary>
		/// 病种等级（用于系统分析）
		/// </summary>
		public int? DiseasesLevel
		{
			get{ return _DiseasesLevel; }
			set
			{
				this.OnPropertyValueChange(_.DiseasesLevel,_DiseasesLevel,value);
				this._DiseasesLevel=value;
			}
		}
		/// <summary>
		/// 住院天数
		/// </summary>
		public int? Days
		{
			get{ return _Days; }
			set
			{
				this.OnPropertyValueChange(_.Days,_Days,value);
				this._Days=value;
			}
		}
		/// <summary>
		/// 治疗费用
		/// </summary>
		public decimal? Cost
		{
			get{ return _Cost; }
			set
			{
				this.OnPropertyValueChange(_.Cost,_Cost,value);
				this._Cost=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Code,
				_.InsideCode};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Code,
				_.InsideCode,
				_.Name,
				_.SearchCode,
				_.DiseasesLevel,
				_.Days,
				_.Cost};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Code,
				this._InsideCode,
				this._Name,
				this._SearchCode,
				this._DiseasesLevel,
				this._Days,
				this._Cost};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_Dic_ICD");
			/// <summary>
			/// 疾病代码
			/// </summary>
			public readonly static Field Code = new Field("Code","Sys_Dic_ICD","疾病代码");
			/// <summary>
			/// 医院内部编码（如果没有则和Code一致）
			/// </summary>
			public readonly static Field InsideCode = new Field("InsideCode","Sys_Dic_ICD","医院内部编码（如果没有则和Code一致）");
			/// <summary>
			/// 疾病名称
			/// </summary>
			public readonly static Field Name = new Field("Name","Sys_Dic_ICD","疾病名称");
			/// <summary>
			/// 检索码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","Sys_Dic_ICD","检索码");
			/// <summary>
			/// 病种等级（用于系统分析）
			/// </summary>
			public readonly static Field DiseasesLevel = new Field("DiseasesLevel","Sys_Dic_ICD","病种等级（用于系统分析）");
			/// <summary>
			/// 住院天数
			/// </summary>
			public readonly static Field Days = new Field("Days","Sys_Dic_ICD","住院天数");
			/// <summary>
			/// 治疗费用
			/// </summary>
			public readonly static Field Cost = new Field("Cost","Sys_Dic_ICD","治疗费用");
		}
		#endregion


	}
}

