//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类TP_DataSource 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TP_DataSource")]
	[Serializable]
	public partial class TP_DataSource : Entity 
	{
		#region Model
		private string _ID;
		private string _Name;
		private int? _Type;
		private string _Script;
		private string _Description;
		private int? _No;
		private string _SearchCode;
		private string _SpellCode;
		private string _WubiCode;
		private int? _Status;
		private DateTime _UpdateTime;
		private string _UpdatorID;
		/// <summary>
		/// 编号
		/// </summary>
		public string ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 类型
		/// </summary>
		public int? Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 脚本
		/// </summary>
		public string Script
		{
			get{ return _Script; }
			set
			{
				this.OnPropertyValueChange(_.Script,_Script,value);
				this._Script=value;
			}
		}
		/// <summary>
		/// 描述
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int? No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange(_.No,_No,value);
				this._No=value;
			}
		}
		/// <summary>
		/// 检索码
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		/// <summary>
		/// 拼音码
		/// </summary>
		public string SpellCode
		{
			get{ return _SpellCode; }
			set
			{
				this.OnPropertyValueChange(_.SpellCode,_SpellCode,value);
				this._SpellCode=value;
			}
		}
		/// <summary>
		/// 五笔码
		/// </summary>
		public string WubiCode
		{
			get{ return _WubiCode; }
			set
			{
				this.OnPropertyValueChange(_.WubiCode,_WubiCode,value);
				this._WubiCode=value;
			}
		}
		/// <summary>
		/// 状态 0停用 1启用
		/// </summary>
		public int? Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新人编号
		/// </summary>
		public string UpdatorID
		{
			get{ return _UpdatorID; }
			set
			{
				this.OnPropertyValueChange(_.UpdatorID,_UpdatorID,value);
				this._UpdatorID=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Name,
				_.Type,
				_.Script,
				_.Description,
				_.No,
				_.SearchCode,
				_.SpellCode,
				_.WubiCode,
				_.Status,
				_.UpdateTime,
				_.UpdatorID};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Name,
				this._Type,
				this._Script,
				this._Description,
				this._No,
				this._SearchCode,
				this._SpellCode,
				this._WubiCode,
				this._Status,
				this._UpdateTime,
				this._UpdatorID};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","TP_DataSource");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field ID = new Field("ID","TP_DataSource","编号");
			/// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name","TP_DataSource","名称");
			/// <summary>
			/// 类型
			/// </summary>
			public readonly static Field Type = new Field("Type","TP_DataSource","类型");
			/// <summary>
			/// 脚本
			/// </summary>
			public readonly static Field Script = new Field("Script","TP_DataSource","脚本");
			/// <summary>
			/// 描述
			/// </summary>
			public readonly static Field Description = new Field("Description","TP_DataSource","描述");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field No = new Field("No","TP_DataSource","排序");
			/// <summary>
			/// 检索码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","TP_DataSource","检索码");
			/// <summary>
			/// 拼音码
			/// </summary>
			public readonly static Field SpellCode = new Field("SpellCode","TP_DataSource","拼音码");
			/// <summary>
			/// 五笔码
			/// </summary>
			public readonly static Field WubiCode = new Field("WubiCode","TP_DataSource","五笔码");
			/// <summary>
			/// 状态 0停用 1启用
			/// </summary>
			public readonly static Field Status = new Field("Status","TP_DataSource","状态 0停用 1启用");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","TP_DataSource","更新时间");
			/// <summary>
			/// 更新人编号
			/// </summary>
			public readonly static Field UpdatorID = new Field("UpdatorID","TP_DataSource","更新人编号");
		}
		#endregion


	}
}

