//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类TP_KnowlageCategory 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TP_KnowlageCategory")]
	[Serializable]
	public partial class TP_KnowlageCategory : Entity 
	{
		#region Model
		private string _ID;
		private string _NodeCode;
		private string _ParentCategotyCode;
		private string _CategoryName;
		/// <summary>
		/// 
		/// </summary>
		public string ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NodeCode
		{
			get{ return _NodeCode; }
			set
			{
				this.OnPropertyValueChange(_.NodeCode,_NodeCode,value);
				this._NodeCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ParentCategotyCode
		{
			get{ return _ParentCategotyCode; }
			set
			{
				this.OnPropertyValueChange(_.ParentCategotyCode,_ParentCategotyCode,value);
				this._ParentCategotyCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CategoryName
		{
			get{ return _CategoryName; }
			set
			{
				this.OnPropertyValueChange(_.CategoryName,_CategoryName,value);
				this._CategoryName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.NodeCode,
				_.ParentCategotyCode,
				_.CategoryName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._NodeCode,
				this._ParentCategotyCode,
				this._CategoryName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","TP_KnowlageCategory");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","TP_KnowlageCategory","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NodeCode = new Field("NodeCode","TP_KnowlageCategory","NodeCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentCategotyCode = new Field("ParentCategotyCode","TP_KnowlageCategory","ParentCategotyCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CategoryName = new Field("CategoryName","TP_KnowlageCategory","CategoryName");
		}
		#endregion


	}
}

