//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类TP_Range 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TP_Range")]
	[Serializable]
	public partial class TP_Range : Entity 
	{
		#region Model
		private string _RangeTypeCode;
		private string _Code;
		private string _Name;
		private int _No;
		private string _SearchCode;
		/// <summary>
		/// 值域类型编码
		/// </summary>
		public string RangeTypeCode
		{
			get{ return _RangeTypeCode; }
			set
			{
				this.OnPropertyValueChange(_.RangeTypeCode,_RangeTypeCode,value);
				this._RangeTypeCode=value;
			}
		}
		/// <summary>
		/// 编码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange(_.No,_No,value);
				this._No=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.RangeTypeCode,
				_.Code};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.RangeTypeCode,
				_.Code,
				_.Name,
				_.No,
				_.SearchCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._RangeTypeCode,
				this._Code,
				this._Name,
				this._No,
				this._SearchCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","TP_Range");
			/// <summary>
			/// 值域类型编码
			/// </summary>
			public readonly static Field RangeTypeCode = new Field("RangeTypeCode","TP_Range","值域类型编码");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Code = new Field("Code","TP_Range","编码");
			/// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name","TP_Range","名称");
			/// <summary>
			/// 序号
			/// </summary>
			public readonly static Field No = new Field("No","TP_Range","序号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","TP_Range","SearchCode");
		}
		#endregion


	}
}

