//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace CIS.Model
{

    /// <summary>
    /// 实体类TP_RangeType 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TP_RangeType")]
	[Serializable]
	public partial class TP_RangeType : Entity 
	{
		#region Model
		private string _Code;
		private string _Name;
		private string _Description;
		private int _Status;
		private string _Updater;
		private DateTime _UpdateDate;
		private int _No;
		private string _SearchCode;
		/// <summary>
		/// 编码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 描述
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 使用标志  0 未使用 1 使用
		/// </summary>
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 更新人编号
		/// </summary>
		public string Updater
		{
			get{ return _Updater; }
			set
			{
				this.OnPropertyValueChange(_.Updater,_Updater,value);
				this._Updater=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateDate
		{
			get{ return _UpdateDate; }
			set
			{
				this.OnPropertyValueChange(_.UpdateDate,_UpdateDate,value);
				this._UpdateDate=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange(_.No,_No,value);
				this._No=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Code};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Code,
				_.Name,
				_.Description,
				_.Status,
				_.Updater,
				_.UpdateDate,
				_.No,
				_.SearchCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Code,
				this._Name,
				this._Description,
				this._Status,
				this._Updater,
				this._UpdateDate,
				this._No,
				this._SearchCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","TP_RangeType");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Code = new Field("Code","TP_RangeType","编码");
			/// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name","TP_RangeType","名称");
			/// <summary>
			/// 描述
			/// </summary>
			public readonly static Field Description = new Field("Description","TP_RangeType","描述");
			/// <summary>
			/// 使用标志  0 未使用 1 使用
			/// </summary>
			public readonly static Field Status = new Field("Status","TP_RangeType","使用标志  0 未使用 1 使用");
			/// <summary>
			/// 更新人编号
			/// </summary>
			public readonly static Field Updater = new Field("Updater","TP_RangeType","更新人编号");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateDate = new Field("UpdateDate","TP_RangeType","更新时间");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field No = new Field("No","TP_RangeType","排序");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","TP_RangeType","SearchCode");
		}
		#endregion


	}
}

