//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
    /// <summary>
    /// 实体类TP_WordLIB_User。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TP_WordLIB_User")]
    [Serializable]
    public partial class TP_WordLIB_User : Entity
    {
        #region Model
        private string _ID;
        private string _WordLIBCode;
        private string _UserCode;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("WordLIBCode")]
        public string WordLIBCode
        {
            get { return _WordLIBCode; }
            set
            {
                this.OnPropertyValueChange("WordLIBCode");
                this._WordLIBCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserCode")]
        public string UserCode
        {
            get { return _UserCode; }
            set
            {
                this.OnPropertyValueChange("UserCode");
                this._UserCode = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.WordLIBCode,
				_.UserCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._WordLIBCode,
				this._UserCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "TP_WordLIB_User");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "TP_WordLIB_User", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WordLIBCode = new Field("WordLIBCode", "TP_WordLIB_User", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UserCode = new Field("UserCode", "TP_WordLIB_User", "");
        }
        #endregion
    }
}