//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CIS.Model
{
	/// <summary>
	/// 实体类YJ_PACS_DR。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("YJ_PACS_DR")]
	[Serializable]
	public partial class YJ_PACS_DR : Entity
	{
		#region Model
		private string _HisPatientID;
		private string _SocietyID;
		private string _ExecDeptID;
		private string _PatientName;
		private string _SexName;
		private DateTime? _Birthday;
		private string _Phonenumber;
		private string _Address;
		private string _ApplicationID;
		private DateTime? _OperateTime;
		private string _ReqDepartmentName;
		private string _ReqDoctorName;
		private string _RoomName;
		private string _SickBed;
		private string _Diagnose;
		private string _Abstracthistory;
		private string _DeviceTypeName;
		private decimal? _Cost;
		private string _ReMark;
		private decimal? _IsFee;
		private decimal? _Isconfirm;
		private string _BRLY;
		private string _JZHBLH;
		private int _CFDH;
		private int _YZID;
		private string _JCXMBM;
		private string _JCXMMC;
		private string _XMBM;
		private string _XMMC;
		private string _XMDW;
		private string _XMGG;
		private decimal? _XMDJ;
		private decimal? _XMSL;
		private string _SQKS;
		private string _ZXKSMC;
		private string _HLKS;
		private string _YSGH;
		private string _CZJC;
		private DateTime? _CZRQ;
		private DateTime _INDATE;
		private int _ID;
		private string _SBLX;
		private string _IDNUMBER;
		private string _PositionName;

		/// <summary>
		/// 
		/// </summary>
		[Field("HisPatientID")]
		public string HisPatientID
		{
			get { return _HisPatientID; }
			set
			{
				this.OnPropertyValueChange("HisPatientID");
				this._HisPatientID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SocietyID")]
		public string SocietyID
		{
			get { return _SocietyID; }
			set
			{
				this.OnPropertyValueChange("SocietyID");
				this._SocietyID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ExecDeptID")]
		public string ExecDeptID
		{
			get { return _ExecDeptID; }
			set
			{
				this.OnPropertyValueChange("ExecDeptID");
				this._ExecDeptID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PatientName")]
		public string PatientName
		{
			get { return _PatientName; }
			set
			{
				this.OnPropertyValueChange("PatientName");
				this._PatientName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SexName")]
		public string SexName
		{
			get { return _SexName; }
			set
			{
				this.OnPropertyValueChange("SexName");
				this._SexName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Birthday")]
		public DateTime? Birthday
		{
			get { return _Birthday; }
			set
			{
				this.OnPropertyValueChange("Birthday");
				this._Birthday = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Phonenumber")]
		public string Phonenumber
		{
			get { return _Phonenumber; }
			set
			{
				this.OnPropertyValueChange("Phonenumber");
				this._Phonenumber = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Address")]
		public string Address
		{
			get { return _Address; }
			set
			{
				this.OnPropertyValueChange("Address");
				this._Address = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ApplicationID")]
		public string ApplicationID
		{
			get { return _ApplicationID; }
			set
			{
				this.OnPropertyValueChange("ApplicationID");
				this._ApplicationID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OperateTime")]
		public DateTime? OperateTime
		{
			get { return _OperateTime; }
			set
			{
				this.OnPropertyValueChange("OperateTime");
				this._OperateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReqDepartmentName")]
		public string ReqDepartmentName
		{
			get { return _ReqDepartmentName; }
			set
			{
				this.OnPropertyValueChange("ReqDepartmentName");
				this._ReqDepartmentName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReqDoctorName")]
		public string ReqDoctorName
		{
			get { return _ReqDoctorName; }
			set
			{
				this.OnPropertyValueChange("ReqDoctorName");
				this._ReqDoctorName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RoomName")]
		public string RoomName
		{
			get { return _RoomName; }
			set
			{
				this.OnPropertyValueChange("RoomName");
				this._RoomName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SickBed")]
		public string SickBed
		{
			get { return _SickBed; }
			set
			{
				this.OnPropertyValueChange("SickBed");
				this._SickBed = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Diagnose")]
		public string Diagnose
		{
			get { return _Diagnose; }
			set
			{
				this.OnPropertyValueChange("Diagnose");
				this._Diagnose = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Abstracthistory")]
		public string Abstracthistory
		{
			get { return _Abstracthistory; }
			set
			{
				this.OnPropertyValueChange("Abstracthistory");
				this._Abstracthistory = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeviceTypeName")]
		public string DeviceTypeName
		{
			get { return _DeviceTypeName; }
			set
			{
				this.OnPropertyValueChange("DeviceTypeName");
				this._DeviceTypeName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Cost")]
		public decimal? Cost
		{
			get { return _Cost; }
			set
			{
				this.OnPropertyValueChange("Cost");
				this._Cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReMark")]
		public string ReMark
		{
			get { return _ReMark; }
			set
			{
				this.OnPropertyValueChange("ReMark");
				this._ReMark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsFee")]
		public decimal? IsFee
		{
			get { return _IsFee; }
			set
			{
				this.OnPropertyValueChange("IsFee");
				this._IsFee = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Isconfirm")]
		public decimal? Isconfirm
		{
			get { return _Isconfirm; }
			set
			{
				this.OnPropertyValueChange("Isconfirm");
				this._Isconfirm = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BRLY")]
		public string BRLY
		{
			get { return _BRLY; }
			set
			{
				this.OnPropertyValueChange("BRLY");
				this._BRLY = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("JZHBLH")]
		public string JZHBLH
		{
			get { return _JZHBLH; }
			set
			{
				this.OnPropertyValueChange("JZHBLH");
				this._JZHBLH = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CFDH")]
		public int CFDH
		{
			get { return _CFDH; }
			set
			{
				this.OnPropertyValueChange("CFDH");
				this._CFDH = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("YZID")]
		public int YZID
		{
			get { return _YZID; }
			set
			{
				this.OnPropertyValueChange("YZID");
				this._YZID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("JCXMBM")]
		public string JCXMBM
		{
			get { return _JCXMBM; }
			set
			{
				this.OnPropertyValueChange("JCXMBM");
				this._JCXMBM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("JCXMMC")]
		public string JCXMMC
		{
			get { return _JCXMMC; }
			set
			{
				this.OnPropertyValueChange("JCXMMC");
				this._JCXMMC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("XMBM")]
		public string XMBM
		{
			get { return _XMBM; }
			set
			{
				this.OnPropertyValueChange("XMBM");
				this._XMBM = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("XMMC")]
		public string XMMC
		{
			get { return _XMMC; }
			set
			{
				this.OnPropertyValueChange("XMMC");
				this._XMMC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("XMDW")]
		public string XMDW
		{
			get { return _XMDW; }
			set
			{
				this.OnPropertyValueChange("XMDW");
				this._XMDW = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("XMGG")]
		public string XMGG
		{
			get { return _XMGG; }
			set
			{
				this.OnPropertyValueChange("XMGG");
				this._XMGG = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("XMDJ")]
		public decimal? XMDJ
		{
			get { return _XMDJ; }
			set
			{
				this.OnPropertyValueChange("XMDJ");
				this._XMDJ = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("XMSL")]
		public decimal? XMSL
		{
			get { return _XMSL; }
			set
			{
				this.OnPropertyValueChange("XMSL");
				this._XMSL = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SQKS")]
		public string SQKS
		{
			get { return _SQKS; }
			set
			{
				this.OnPropertyValueChange("SQKS");
				this._SQKS = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ZXKSMC")]
		public string ZXKSMC
		{
			get { return _ZXKSMC; }
			set
			{
				this.OnPropertyValueChange("ZXKSMC");
				this._ZXKSMC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HLKS")]
		public string HLKS
		{
			get { return _HLKS; }
			set
			{
				this.OnPropertyValueChange("HLKS");
				this._HLKS = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("YSGH")]
		public string YSGH
		{
			get { return _YSGH; }
			set
			{
				this.OnPropertyValueChange("YSGH");
				this._YSGH = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CZJC")]
		public string CZJC
		{
			get { return _CZJC; }
			set
			{
				this.OnPropertyValueChange("CZJC");
				this._CZJC = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CZRQ")]
		public DateTime? CZRQ
		{
			get { return _CZRQ; }
			set
			{
				this.OnPropertyValueChange("CZRQ");
				this._CZRQ = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("INDATE")]
		public DateTime INDATE
		{
			get { return _INDATE; }
			set
			{
				this.OnPropertyValueChange("INDATE");
				this._INDATE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get { return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SBLX")]
		public string SBLX
		{
			get { return _SBLX; }
			set
			{
				this.OnPropertyValueChange("SBLX");
				this._SBLX = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IDNUMBER")]
		public string IDNUMBER
		{
			get { return _IDNUMBER; }
			set
			{
				this.OnPropertyValueChange("IDNUMBER");
				this._IDNUMBER = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PositionName")]
		public string PositionName
		{
			get { return _PositionName; }
			set
			{
				this.OnPropertyValueChange("PositionName");
				this._PositionName = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID,
			};
		}
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ID;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.HisPatientID,
				_.SocietyID,
				_.ExecDeptID,
				_.PatientName,
				_.SexName,
				_.Birthday,
				_.Phonenumber,
				_.Address,
				_.ApplicationID,
				_.OperateTime,
				_.ReqDepartmentName,
				_.ReqDoctorName,
				_.RoomName,
				_.SickBed,
				_.Diagnose,
				_.Abstracthistory,
				_.DeviceTypeName,
				_.Cost,
				_.ReMark,
				_.IsFee,
				_.Isconfirm,
				_.BRLY,
				_.JZHBLH,
				_.CFDH,
				_.YZID,
				_.JCXMBM,
				_.JCXMMC,
				_.XMBM,
				_.XMMC,
				_.XMDW,
				_.XMGG,
				_.XMDJ,
				_.XMSL,
				_.SQKS,
				_.ZXKSMC,
				_.HLKS,
				_.YSGH,
				_.CZJC,
				_.CZRQ,
				_.INDATE,
				_.ID,
				_.SBLX,
				_.IDNUMBER,
				_.PositionName,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._HisPatientID,
				this._SocietyID,
				this._ExecDeptID,
				this._PatientName,
				this._SexName,
				this._Birthday,
				this._Phonenumber,
				this._Address,
				this._ApplicationID,
				this._OperateTime,
				this._ReqDepartmentName,
				this._ReqDoctorName,
				this._RoomName,
				this._SickBed,
				this._Diagnose,
				this._Abstracthistory,
				this._DeviceTypeName,
				this._Cost,
				this._ReMark,
				this._IsFee,
				this._Isconfirm,
				this._BRLY,
				this._JZHBLH,
				this._CFDH,
				this._YZID,
				this._JCXMBM,
				this._JCXMMC,
				this._XMBM,
				this._XMMC,
				this._XMDW,
				this._XMGG,
				this._XMDJ,
				this._XMSL,
				this._SQKS,
				this._ZXKSMC,
				this._HLKS,
				this._YSGH,
				this._CZJC,
				this._CZRQ,
				this._INDATE,
				this._ID,
				this._SBLX,
				this._IDNUMBER,
				this._PositionName,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "YJ_PACS_DR");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HisPatientID = new Field("HisPatientID", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SocietyID = new Field("SocietyID", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExecDeptID = new Field("ExecDeptID", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientName = new Field("PatientName", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SexName = new Field("SexName", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Birthday = new Field("Birthday", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Phonenumber = new Field("Phonenumber", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApplicationID = new Field("ApplicationID", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OperateTime = new Field("OperateTime", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReqDepartmentName = new Field("ReqDepartmentName", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReqDoctorName = new Field("ReqDoctorName", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RoomName = new Field("RoomName", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SickBed = new Field("SickBed", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Diagnose = new Field("Diagnose", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Abstracthistory = new Field("Abstracthistory", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceTypeName = new Field("DeviceTypeName", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Cost = new Field("Cost", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReMark = new Field("ReMark", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsFee = new Field("IsFee", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Isconfirm = new Field("Isconfirm", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BRLY = new Field("BRLY", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JZHBLH = new Field("JZHBLH", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CFDH = new Field("CFDH", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field YZID = new Field("YZID", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JCXMBM = new Field("JCXMBM", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JCXMMC = new Field("JCXMMC", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XMBM = new Field("XMBM", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XMMC = new Field("XMMC", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XMDW = new Field("XMDW", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XMGG = new Field("XMGG", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XMDJ = new Field("XMDJ", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XMSL = new Field("XMSL", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SQKS = new Field("SQKS", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZXKSMC = new Field("ZXKSMC", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HLKS = new Field("HLKS", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field YSGH = new Field("YSGH", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CZJC = new Field("CZJC", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CZRQ = new Field("CZRQ", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field INDATE = new Field("INDATE", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SBLX = new Field("SBLX", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IDNUMBER = new Field("IDNUMBER", "YJ_PACS_DR", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PositionName = new Field("PositionName", "YJ_PACS_DR", "");
		}
		#endregion
	}
}